<?php

namespace Database\Seeders;

use App\Models\Country;
use App\Models\Governorate;
use App\Models\City;
use App\Models\District;
use Illuminate\Database\Seeder;

class GeographyFullSeeder extends Seeder
{
    public function run(): void
    {
        $egypt = Country::updateOrCreate(
            ['code' => 'EG'],
            [
                'iso2' => 'EG',
                'name' => 'مصر',
                'name_en' => 'Egypt',
                'phone_code' => '+20',
            ]
        );

        $governoratesData = [
            ['name' => 'القاهرة', 'code' => 'CAI'],
            ['name' => 'الإسكندرية', 'code' => 'ALX'],
            ['name' => 'الجيزة', 'code' => 'GIZ'],
            ['name' => 'القليوبية', 'code' => 'QLY'],
            ['name' => 'الشرقية', 'code' => 'SHQ'],
            ['name' => 'الدقهلية', 'code' => 'DKL'],
            ['name' => 'البحيرة', 'code' => 'BHR'],
            ['name' => 'كفر الشيخ', 'code' => 'KFS'],
            ['name' => 'الغربية', 'code' => 'GHR'],
            ['name' => 'المنوفية', 'code' => 'MNF'],
            ['name' => 'بني سويف', 'code' => 'BNS'],
            ['name' => 'الفيوم', 'code' => 'FYM'],
            ['name' => 'المنيا', 'code' => 'MIN'],
            ['name' => 'أسيوط', 'code' => 'AST'],
            ['name' => 'سوهاج', 'code' => 'SHG'],
            ['name' => 'قنا', 'code' => 'QEN'],
            ['name' => 'الأقصر', 'code' => 'LUX'],
            ['name' => 'أسوان', 'code' => 'ASM'],
            ['name' => 'البحر الأحمر', 'code' => 'BAH'],
            ['name' => 'الوادي الجديد', 'code' => 'WAD'],
            ['name' => 'مطروح', 'code' => 'MTN'],
            ['name' => 'شمال سيناء', 'code' => 'SIN'],
            ['name' => 'جنوب سيناء', 'code' => 'JSN'],
            ['name' => 'بورسعيد', 'code' => 'PTS'],
            ['name' => 'السويس', 'code' => 'SUZ'],
            ['name' => 'الإسماعيلية', 'code' => 'ISM'],
            ['name' => 'دمياط', 'code' => 'DAM'],
        ];

        $govModels = [];
        foreach ($governoratesData as $gov) {
            $govModels[$gov['name']] = Governorate::updateOrCreate(
                ['name' => $gov['name'], 'country_id' => $egypt->id],
                ['code' => $gov['code']]
            );
        }

        $citiesData = [
            ['governorate_name' => 'القاهرة', 'name' => 'القاهرة الكبرى', 'name_en' => 'Greater Cairo'],
            ['governorate_name' => 'القاهرة', 'name' => 'حلوان', 'name_en' => 'Helwan'],
            ['governorate_name' => 'القاهرة', 'name' => 'شبرا الخيمة', 'name_en' => 'Shubra El Kheima'],
            ['governorate_name' => 'الإسكندرية', 'name' => 'الإسكندرية المركز', 'name_en' => 'Alexandria Central'],
            ['governorate_name' => 'الإسكندرية', 'name' => 'الإسكندرية الجديدة', 'name_en' => 'New Alexandria'],
            ['governorate_name' => 'الإسكندرية', 'name' => 'الإبراهيمية', 'name_en' => 'Al Ibrahimia'],
            ['governorate_name' => 'الإسكندرية', 'name' => 'المنتزة', 'name_en' => 'Al Montaza'],
            ['governorate_name' => 'الجيزة', 'name' => 'الجيزة المركز', 'name_en' => 'Giza Central'],
            ['governorate_name' => 'الجيزة', 'name' => 'الهرم', 'name_en' => 'Al Haram'],
            ['governorate_name' => 'الجيزة', 'name' => 'الفيوم', 'name_en' => 'Al Fayoum'],
            ['governorate_name' => 'الجيزة', 'name' => 'أوسيم', 'name_en' => 'Osim'],
            ['governorate_name' => 'الجيزة', 'name' => 'العياط', 'name_en' => 'Al Ayat'],
            ['governorate_name' => 'الجيزة', 'name' => 'البدرشين', 'name_en' => 'Al Badrasheen'],
            ['governorate_name' => 'الجيزة', 'name' => 'الساحل', 'name_en' => 'Al Sahel'],
            ['governorate_name' => 'القليوبية', 'name' => 'بنها', 'name_en' => 'Banha'],
            ['governorate_name' => 'القليوبية', 'name' => 'شبرا الخيمة', 'name_en' => 'Shubra El Kheima'],
            ['governorate_name' => 'القليوبية', 'name' => 'قليوب', 'name_en' => 'Qalyub'],
            ['governorate_name' => 'القليوبية', 'name' => 'القناطر الخيرية', 'name_en' => 'Al Qanatir Al Khairia'],
            ['governorate_name' => 'القليوبية', 'name' => 'الخانكة', 'name_en' => 'Al Khanka'],
            ['governorate_name' => 'القليوبية', 'name' => 'كفر شكر', 'name_en' => 'Kafr Shukr'],
            ['governorate_name' => 'الشرقية', 'name' => 'الزقازيق', 'name_en' => 'Zagazig'],
            ['governorate_name' => 'الشرقية', 'name' => 'العاشر من رمضان', 'name_en' => '10th of Ramadan'],
            ['governorate_name' => 'الشرقية', 'name' => 'بلبيس', 'name_en' => 'Belbeis'],
            ['governorate_name' => 'الشرقية', 'name' => 'الإبراهيمية', 'name_en' => 'Al Ibrahimia'],
            ['governorate_name' => 'الشرقية', 'name' => 'أبو حماد', 'name_en' => 'Abu Hammad'],
            ['governorate_name' => 'الشرقية', 'name' => 'أبو كبير', 'name_en' => 'Abu Kebir'],
            ['governorate_name' => 'الشرقية', 'name' => 'ههيا', 'name_en' => 'Hehia'],
            ['governorate_name' => 'الشرقية', 'name' => 'فاقوس', 'name_en' => 'Fakous'],
            ['governorate_name' => 'الدقهلية', 'name' => 'المنصورة', 'name_en' => 'Mansoura'],
            ['governorate_name' => 'الدقهلية', 'name' => 'دكرور', 'name_en' => 'Dekernes'],
            ['governorate_name' => 'الدقهلية', 'name' => 'طلخا', 'name_en' => 'Talkha'],
            ['governorate_name' => 'الدقهلية', 'name' => 'منية النصر', 'name_en' => 'Menia El Nasr'],
            ['governorate_name' => 'الدقهلية', 'name' => 'السنبلاوين', 'name_en' => 'El Simbillawin'],
            ['governorate_name' => 'الدقهلية', 'name' => 'أجا', 'name_en' => 'Aga'],
            ['governorate_name' => 'الدقهلية', 'name' => 'ميت غمر', 'name_en' => 'Mit Gamr'],
            ['governorate_name' => 'الدقهلية', 'name' => 'الجمالية', 'name_en' => 'El Gamalia'],
            ['governorate_name' => 'البحيرة', 'name' => 'دمنهور', 'name_en' => 'Damanhour'],
            ['governorate_name' => 'البحيرة', 'name' => 'الإسكندرية', 'name_en' => 'Alexandria'],
            ['governorate_name' => 'البحيرة', 'name' => 'كفر الدوار', 'name_en' => 'Kafr El Dawwar'],
            ['governorate_name' => 'البحيرة', 'name' => 'رشيد', 'name_en' => 'Rashid'],
            ['governorate_name' => 'البحيرة', 'name' => 'أبو حمص', 'name_en' => 'Abu Hummus'],
            ['governorate_name' => 'البحيرة', 'name' => 'الدلنجات', 'name_en' => 'Delengat'],
            ['governorate_name' => 'البحيرة', 'name' => 'المحلة الكبرى', 'name_en' => 'El Mahalla El Kubra'],
            ['governorate_name' => 'البحيرة', 'name' => 'boltim', 'name_en' => 'Baltim'],
            ['governorate_name' => 'كفر الشيخ', 'name' => 'كفر الشيخ', 'name_en' => 'Kafr El Sheikh'],
            ['governorate_name' => 'كفر الشيخ', 'name' => 'دسوق', 'name_en' => 'Desouk'],
            ['governorate_name' => 'كفر الشيخ', 'name' => 'سيدي سالم', 'name_en' => 'Sidi Salem'],
            ['governorate_name' => 'كفر الشيخ', 'name' => 'الحامول', 'name_en' => 'El Hamoul'],
            ['governorate_name' => 'كفر الشيخ', 'name' => 'بيلا', 'name_en' => 'Bella'],
            ['governorate_name' => 'كفر الشيخ', 'name' => 'الرياض', 'name_en' => 'El Riyad'],
            ['governorate_name' => 'الغربية', 'name' => 'المحلة الكبرى', 'name_en' => 'El Mahalla El Kubra'],
            ['governorate_name' => 'الغربية', 'name' => 'طنطا', 'name_en' => 'Tanta'],
            ['governorate_name' => 'الغربية', 'name' => 'الغربية', 'name_en' => 'Gharbia'],
            ['governorate_name' => 'الغربية', 'name' => 'كفر الزيات', 'name_en' => 'Kafr El Zayat'],
            ['governorate_name' => 'الغربية', 'name' => 'زفتى', 'name_en' => 'Zefta'],
            ['governorate_name' => 'الغربية', 'name' => 'السنطة', 'name_en' => 'El Santa'],
            ['governorate_name' => 'المنوفية', 'name' => 'شبين الكوم', 'name_en' => 'Shebin El Kom'],
            ['governorate_name' => 'المنوفية', 'name' => 'منوف', 'name_en' => 'Menouf'],
            ['governorate_name' => 'المنوفية', 'name' => 'السادات', 'name_en' => 'El Sadat'],
            ['governorate_name' => 'المنوفية', 'name' => 'أشمون', 'name_en' => 'Ashmoun'],
            ['governorate_name' => 'المنوفية', 'name' => 'الباجور', 'name_en' => 'El Bagour'],
            ['governorate_name' => 'المنوفية', 'name' => 'قرية بالحو', 'name_en' => 'Qesm Bargil'],
            ['governorate_name' => 'بني سويف', 'name' => 'بني سويف', 'name_en' => 'Beni Suef'],
            ['governorate_name' => 'بني سويف', 'name' => 'الواسطى', 'name_en' => 'El Wasta'],
            ['governorate_name' => 'بني سويف', 'name' => 'ناصج', 'name_en' => 'Naser'],
            ['governorate_name' => 'بني سويف', 'name' => 'إهناسيا', 'name_en' => 'Ihnasia'],
            ['governorate_name' => 'بني سويف', 'name' => 'ببا', 'name_en' => 'Biba'],
            ['governorate_name' => 'بني سويف', 'name' => 'سمسطا', 'name_en' => 'Somasta'],
            ['governorate_name' => 'الفيوم', 'name' => 'الفيوم', 'name_en' => 'Fayoum'],
            ['governorate_name' => 'الفيوم', 'name' => 'الفيوم الجديدة', 'name_en' => 'New Fayoum'],
            ['governorate_name' => 'الفيوم', 'name' => 'طامية', 'name_en' => 'Tamiya'],
            ['governorate_name' => 'الفيوم', 'name' => 'سنورس', 'name_en' => 'Sinnurs'],
            ['governorate_name' => 'الفيوم', 'name' => 'إطسا', 'name_en' => 'Etsa'],
            ['governorate_name' => 'الفيوم', 'name' => 'الزمالك', 'name_en' => 'El Zamalek'],
            ['governorate_name' => 'المنيا', 'name' => 'المنيا', 'name_en' => 'Minya'],
            ['governorate_name' => 'المنيا', 'name' => 'المنيا الجديدة', 'name_en' => 'New Minya'],
            ['governorate_name' => 'المنيا', 'name' => 'مغاغة', 'name_en' => 'Maghagha'],
            ['governorate_name' => 'المنيا', 'name' => 'بني مزار', 'name_en' => 'Bani Mazar'],
            ['governorate_name' => 'المنيا', 'name' => 'melawi', 'name_en' => 'Melawi'],
            ['governorate_name' => 'المنيا', 'name' => 'أبو تيج', 'name_en' => 'Abu Tisht'],
            ['governorate_name' => 'المنيا', 'name' => 'دير مواس', 'name_en' => 'Deir Mawas'],
            ['governorate_name' => 'أسيوط', 'name' => 'أسيوط', 'name_en' => 'Assiut'],
            ['governorate_name' => 'أسيوط', 'name' => 'أسيوط الجديدة', 'name_en' => 'New Assiut'],
            ['governorate_name' => 'أسيوط', 'name' => 'ال新华村', 'name_en' => 'El Badari'],
            ['governorate_name' => 'أسيوط', 'name' => 'القوصية', 'name_en' => 'El Qusiya'],
            ['governorate_name' => 'أسيوط', 'name' => 'منفلوط', 'name_en' => 'Manfalut'],
            ['governorate_name' => 'أسيوط', 'name' => 'أبو تيج', 'name_en' => 'Abu Teeg'],
            ['governorate_name' => 'أسيوط', 'name' => 'صدفا', 'name_en' => 'Sodfa'],
            ['governorate_name' => 'سوهاج', 'name' => 'سوهاج', 'name_en' => 'Sohag'],
            ['governorate_name' => 'سوهاج', 'name' => 'سوهاج الجديدة', 'name_en' => 'New Sohag'],
            ['governorate_name' => 'سوهاج', 'name' => 'أخميم', 'name_en' => 'Akhmim'],
            ['governorate_name' => 'سوهاج', 'name' => 'ال BALINA', 'name_en' => 'El Balina'],
            ['governorate_name' => 'سوهاج', 'name' => 'جهينة', 'name_en' => 'Juhayna'],
            ['governorate_name' => 'سوهاج', 'name' => 'المراغة', 'name_en' => 'El Maragha'],
            ['governorate_name' => 'سوهاج', 'name' => 'طما', 'name_en' => 'Tima'],
            ['governorate_name' => 'قنا', 'name' => 'قنا', 'name_en' => 'Qena'],
            ['governorate_name' => 'قنا', 'name' => 'قنا الجديدة', 'name_en' => 'New Qena'],
            ['governorate_name' => 'قنا', 'name' => 'الأقصر', 'name_en' => 'Luxor'],
            ['governorate_name' => 'قنا', 'name' => 'ال BALINA', 'name_en' => 'El Balina'],
            ['governorate_name' => 'قنا', 'name' => 'نجع حمادي', 'name_en' => 'Nag Hammadi'],
            ['governorate_name' => 'قنا', 'name' => 'دشنا', 'name_en' => 'Deshna'],
            ['governorate_name' => 'قنا', 'name' => 'فوكة', 'name_en' => 'Fuqa'],
            ['governorate_name' => 'الأقصر', 'name' => 'الأقصر', 'name_en' => 'Luxor'],
            ['governorate_name' => 'الأقصر', 'name' => 'الأقصر الجديدة', 'name_en' => 'New Luxor'],
            ['governorate_name' => 'الأقصر', 'name' => 'اليرموك', 'name_en' => 'Al Yarmouk'],
            ['governorate_name' => 'الأقصر', 'name' => 'البياضية', 'name_en' => 'El Bayadia'],
            ['governorate_name' => 'الأقصر', 'name' => 'طيبة', 'name_en' => 'Thebes'],
            ['governorate_name' => 'أسوان', 'name' => 'أسوان', 'name_en' => 'Aswan'],
            ['governorate_name' => 'أسوان', 'name' => 'أسوان الجديدة', 'name_en' => 'New Aswan'],
            ['governorate_name' => 'أسوان', 'name' => 'دراو', 'name_en' => 'Daraw'],
            ['governorate_name' => 'أسوان', 'name' => 'كوم أمبو', 'name_en' => 'Kom Ombo'],
            ['governorate_name' => 'أسوان', 'name' => 'نصر النوبة', 'name_en' => 'Nasr Nubia'],
            ['governorate_name' => 'البحر الأحمر', 'name' => 'الغردقة', 'name_en' => 'Hurghada'],
            ['governorate_name' => 'البحر الأحمر', 'name' => 'الغردقة الجديدة', 'name_en' => 'New Hurghada'],
            ['governorate_name' => 'البحر الأحمر', 'name' => 'السلوم', 'name_en' => 'Salloum'],
            ['governorate_name' => 'البحر الأحمر', 'name' => 'الجونة', 'name_en' => 'El Gouna'],
            ['governorate_name' => 'البحر الأحمر', 'name' => 'مرسى علم', 'name_en' => 'Marsa Alam'],
            ['governorate_name' => 'الوادي الجديد', 'name' => 'الخارجة', 'name_en' => 'El Kharga'],
            ['governorate_name' => 'الوادي الجديد', 'name' => 'الد淋ة', 'name_en' => 'El Dakhla'],
            ['governorate_name' => 'الوادي الجديد', 'name' => 'الفرافرة', 'name_en' => 'El Farafra'],
            ['governorate_name' => 'الوادي الجديد', 'name' => 'البليدة', 'name_en' => 'El Balat'],
            ['governorate_name' => 'مطروح', 'name' => 'مطروح', 'name_en' => 'Matrouh'],
            ['governorate_name' => 'مطروح', 'name' => 'الحمام', 'name_en' => 'El Hamam'],
            ['governorate_name' => 'مطروح', 'name' => 'العلمين', 'name_en' => 'El Alamein'],
            ['governorate_name' => 'مطروح', 'name' => 'سيدي براني', 'name_en' => 'Sidi Barrani'],
            ['governorate_name' => 'مطروح', 'name' => 'السلوم', 'name_en' => 'Salloum'],
            ['governorate_name' => 'شمال سيناء', 'name' => 'العريش', 'name_en' => 'El Arish'],
            ['governorate_name' => 'شمال سيناء', 'name' => 'رفح', 'name_en' => 'Rafah'],
            ['governorate_name' => 'شمال سيناء', 'name' => 'بئر العبد', 'name_en' => 'Bir El Abd'],
            ['governorate_name' => 'شمال سيناء', 'name' => 'الحسنة', 'name_en' => 'El Hasna'],
            ['governorate_name' => 'جنوب سيناء', 'name' => 'تور Sinai', 'name_en' => 'Tor Sinai'],
            ['governorate_name' => 'جنوب سيناء', 'name' => 'شرم الشيخ', 'name_en' => 'Sharm El Sheikh'],
            ['governorate_name' => 'جنوب سيناء', 'name' => 'دهب', 'name_en' => 'Dahab'],
            ['governorate_name' => 'جنوب سيناء', 'name' => 'أبو زنيمة', 'name_en' => 'Abu Zunaima'],
            ['governorate_name' => 'جنوب سيناء', 'name' => 'سانت كاترين', 'name_en' => 'Saint Catherine'],
            ['governorate_name' => 'بورسعيد', 'name' => 'بورسعيد', 'name_en' => 'Port Said'],
            ['governorate_name' => 'بورسعيد', 'name' => 'بورسعيد الجديدة', 'name_en' => 'New Port Said'],
            ['governorate_name' => 'السويس', 'name' => 'السويس', 'name_en' => 'Suez'],
            ['governorate_name' => 'السويس', 'name' => 'عتاقة', 'name_en' => 'Ataqa'],
            ['governorate_name' => 'الإسماعيلية', 'name' => 'الإسماعيلية', 'name_en' => 'Ismailia'],
            ['governorate_name' => 'الإسماعيلية', 'name' => 'الإسماعيلية الجديدة', 'name_en' => 'New Ismailia'],
            ['governorate_name' => 'الإسماعيلية', 'name' => 'التجمع', 'name_en' => 'El Takamol'],
            ['governorate_name' => 'الإسماعيلية', 'name' => 'القنطرة شرق', 'name_en' => 'Qantara East'],
            ['governorate_name' => 'الإسماعيلية', 'name' => 'القنطرة غرب', 'name_en' => 'Qantara West'],
            ['governorate_name' => 'دمياط', 'name' => 'دمياط', 'name_en' => 'Damietta'],
            ['governorate_name' => 'دمياط', 'name' => 'دمياط الجديدة', 'name_en' => 'New Damietta'],
            ['governorate_name' => 'دمياط', 'name' => 'الروضة', 'name_en' => 'El Roda'],
            ['governorate_name' => 'دمياط', 'name' => 'فارسكور', 'name_en' => 'Farskor'],
            ['governorate_name' => 'الإسكندرية', 'name' => 'العامرية', 'name_en' => 'Al Amriya'],
            ['governorate_name' => 'الإسكندرية', 'name' => 'العجمى', 'name_en' => 'Al Agamy'],
        ];

        $cityModels = [];
        foreach ($citiesData as $city) {
            $govId = $govModels[$city['governorate_name']]->id;
            $cityModels[$city['governorate_name'] . '_' . $city['name']] = City::updateOrCreate(
                ['name' => $city['name'], 'governorate_id' => $govId],
                ['name_en' => $city['name_en'] ?? null]
            );
        }

        $districtsData = [
            ['city_gov' => 'القاهرة_القاهرة الكبرى', 'name' => 'وسط البلد'],
            ['city_gov' => 'القاهرة_القاهرة الكبرى', 'name' => 'المعادي'],
            ['city_gov' => 'القاهرة_القاهرة الكبرى', 'name' => 'مصر الجديدة'],
            ['city_gov' => 'القاهرة_القاهرة الكبرى', 'name' => 'مدينة نصر'],
            ['city_gov' => 'القاهرة_القاهرة الكبرى', 'name' => 'التجمع الخامس'],
            ['city_gov' => 'القاهرة_القاهرة الكبرى', 'name' => 'الزمالك'],
            ['city_gov' => 'القاهرة_القاهرة الكبرى', 'name' => 'مصر القديمة'],
            ['city_gov' => 'القاهرة_القاهرة الكبرى', 'name' => 'العباسية'],
            ['city_gov' => 'القاهرة_القاهرة الكبرى', 'name' => 'الظاهر'],
            ['city_gov' => 'القاهرة_القاهرة الكبرى', 'name' => 'الشرابية'],
            ['city_gov' => 'القاهرة_القاهرة الكبرى', 'name' => 'المرج'],
            ['city_gov' => 'القاهرة_القاهرة الكبرى', 'name' => 'المطرية'],
            ['city_gov' => 'القاهرة_القاهرة الكبرى', 'name' => 'النزهة'],
            ['city_gov' => 'القاهرة_القاهرة الكبرى', 'name' => 'شبرا'],
            ['city_gov' => 'القاهرة_القاهرة الكبرى', 'name' => 'الوايلي'],
            ['city_gov' => 'القاهرة_القاهرة الكبرى', 'name' => 'باب الشعرية'],
            ['city_gov' => 'القاهرة_القاهرة الكبرى', 'name' => 'القلعة'],
            ['city_gov' => 'القاهرة_القاهرة الكبرى', 'name' => 'الروضه'],
            ['city_gov' => 'القاهرة_القاهرة الكبرى', 'name' => 'دار السلام'],
            ['city_gov' => 'القاهرة_القاهرة الكبرى', 'name' => 'البساتين'],
            ['city_gov' => 'القاهرة_القاهرة الكبرى', 'name' => 'مطرد'],
            ['city_gov' => 'القاهرة_القاهرة الكبرى', 'name' => 'الخليفة'],
            ['city_gov' => 'القاهرة_القاهرة الكبرى', 'name' => 'الساحل'],
            ['city_gov' => 'القاهرة_القاهرة الكبرى', 'name' => 'التبين'],
            ['city_gov' => 'القاهرة_القاهرة الكبرى', 'name' => 'حدائق حلوان'],
            ['city_gov' => 'القاهرة_القاهرة الكبرى', 'name' => 'المعصرة'],
            ['city_gov' => 'القاهرة_القاهرة الكبرى', 'name' => 'طرة'],
            ['city_gov' => 'القاهرة_حلوان', 'name' => 'حلوان المركز'],
            ['city_gov' => 'القاهرة_حلوان', 'name' => 'عين حلوان'],
            ['city_gov' => 'القاهرة_حلوان', 'name' => 'المعصرة'],
            ['city_gov' => 'القاهرة_شبرا الخيمة', 'name' => 'شبرا المركز'],
            ['city_gov' => 'القاهرة_شبرا الخيمة', 'name' => 'الخلفاوي'],
            ['city_gov' => 'القاهرة_شبرا الخيمة', 'name' => 'كفر شبرا'],
            ['city_gov' => 'الإسكندرية_الإسكندرية المركز', 'name' => 'المحطة'],
            ['city_gov' => 'الإسكندرية_الإسكندرية المركز', 'name' => 'الجمرك'],
            ['city_gov' => 'الإسكندرية_الإسكندرية المركز', 'name' => 'الرمل'],
            ['city_gov' => 'الإسكندرية_الإسكندرية المركز', 'name' => 'باب شرق'],
            ['city_gov' => 'الإسكندرية_الإسكندرية المركز', 'name' => 'العصافرة'],
            ['city_gov' => 'الإسكندرية_الإسكندرية المركز', 'name' => 'سيدي جابر'],
            ['city_gov' => 'الإسكندرية_الإسكندرية المركز', 'name' => 'Leban'],
            ['city_gov' => 'الإسكندرية_الإسكندرية المركز', 'name' => 'المنشية'],
            ['city_gov' => 'الإسكندرية_الإسكندرية المركز', 'name' => 'جليم'],
            ['city_gov' => 'الإسكندرية_الإسكندرية المركز', 'name' => 'سموحة'],
            ['city_gov' => 'الإسكندرية_الإسكندرية المركز', 'name' => 'سيدي بشر'],
            ['city_gov' => 'الإسكندرية_الإسكندرية المركز', 'name' => 'الليمان'],
            ['city_gov' => 'الإسكندرية_الإسكندرية الجديدة', 'name' => 'Almirovelopment zone'],
            ['city_gov' => 'الإسكندرية_الإسكندرية الجديدة', 'name' => 'الحضرة الجديدة'],
            ['city_gov' => 'الإسكندرية_الإبراهيمية', 'name' => 'الإبراهيمية المركز'],
            ['city_gov' => 'الإسكندرية_الإبراهيمية', 'name' => 'العجمي'],
            ['city_gov' => 'الإسكندرية_المنتزة', 'name' => 'المنتزة'],
            ['city_gov' => 'الإسكندرية_المنتزة', 'name' => 'Shenzen Bay'],
            ['city_gov' => 'الإسكندرية_المنتزة', 'name' => 'الهانوفيل'],
            ['city_gov' => 'الجيزة_الجيزة المركز', 'name' => 'الجيزة المركز'],
            ['city_gov' => 'الجيزة_الجيزة المركز', 'name' => 'الدقي'],
            ['city_gov' => 'الجيزة_الجيزة المركز', 'name' => 'المهندسين'],
            ['city_gov' => 'الجيزة_الجيزة المركز', 'name' => 'العجوزة'],
            ['city_gov' => 'الجيزة_الجيزة المركز', 'name' => 'الزمالك'],
            ['city_gov' => 'الجيزة_الهرم', 'name' => 'الهرم'],
            ['city_gov' => 'الجيزة_الهرم', 'name' => 'الصف'],
            ['city_gov' => 'الجيزة_الهرم', 'name' => 'العريش'],
            ['city_gov' => 'الجيزة_الفيوم', 'name' => 'الفيوم المركز'],
            ['city_gov' => 'الجيزة_الفيوم', 'name' => 'الصمان'],
            ['city_gov' => 'الجيزة_أوسيم', 'name' => 'أوسيم'],
            ['city_gov' => 'الجيزة_أوسيم', 'name' => 'كرداسة'],
            ['city_gov' => 'الجيزة_العياط', 'name' => 'العياط'],
            ['city_gov' => 'الجيزة_العياط', 'name' => 'البدرشين'],
            ['city_gov' => 'القليوبية_بنها', 'name' => 'بنها المركز'],
            ['city_gov' => 'القليوبية_بنها', 'name' => 'قليوب'],
            ['city_gov' => 'القليوبية_بنها', 'name' => 'القناطر الخيرية'],
            ['city_gov' => 'القليوبية_بنها', 'name' => 'الخانكة'],
            ['city_gov' => 'القليوبية_بنها', 'name' => 'كفر شكر'],
            ['city_gov' => 'القليوبية_بنها', 'name' => 'طوخ'],
            ['city_gov' => 'الشرقية_الزقازيق', 'name' => 'الزقازيق المركز'],
            ['city_gov' => 'الشرقية_الزقازيق', 'name' => 'العاشر من رمضان'],
            ['city_gov' => 'الشرقية_الزقازيق', 'name' => 'بلبيس'],
            ['city_gov' => 'الشرقية_الزقازيق', 'name' => 'الإبراهيمية'],
            ['city_gov' => 'الشرقية_الزقازيق', 'name' => 'أبو حماد'],
            ['city_gov' => 'الشرقية_الزقازيق', 'name' => 'أبو كبير'],
            ['city_gov' => 'الشرقية_الزقازيق', 'name' => 'ههيا'],
            ['city_gov' => 'الشرقية_الزقازيق', 'name' => 'فاقوس'],
            ['city_gov' => 'الدقهلية_المنصورة', 'name' => 'المنصورة المركز'],
            ['city_gov' => 'الدقهلية_المنصورة', 'name' => 'دكرور'],
            ['city_gov' => 'الدقهلية_المنصورة', 'name' => 'طلخا'],
            ['city_gov' => 'الدقهلية_المنصورة', 'name' => 'منية النصر'],
            ['city_gov' => 'الدقهلية_المنصورة', 'name' => 'السنبلاوين'],
            ['city_gov' => 'الدقهلية_المنصورة', 'name' => 'أجا'],
            ['city_gov' => 'الدقهلية_المنصورة', 'name' => 'ميت غمر'],
            ['city_gov' => 'البحيرة_دمنهور', 'name' => 'دمنهور المركز'],
            ['city_gov' => 'البحيرة_دمنهور', 'name' => 'كفر الدوار'],
            ['city_gov' => 'البحيرة_دمنهور', 'name' => 'رشيد'],
            ['city_gov' => 'البحيرة_دمنهور', 'name' => 'أبو حمص'],
            ['city_gov' => 'البحيرة_دمنهور', 'name' => 'الدلنجات'],
            ['city_gov' => 'كفر الشيخ_كفر الشيخ', 'name' => 'كفر الشيخ المركز'],
            ['city_gov' => 'كفر الشيخ_كفر الشيخ', 'name' => 'دسوق'],
            ['city_gov' => 'كفر الشيخ_كفر الشيخ', 'name' => 'سيدي سالم'],
            ['city_gov' => 'كفر الشيخ_كفر الشيخ', 'name' => 'الحامول'],
            ['city_gov' => 'كفر الشيخ_كفر الشيخ', 'name' => 'بيلا'],
            ['city_gov' => 'الغربية_طنطا', 'name' => 'طنطا المركز'],
            ['city_gov' => 'الغربية_طنطا', 'name' => 'المحلة الكبرى'],
            ['city_gov' => 'الغربية_طنطا', 'name' => 'كفر الزيات'],
            ['city_gov' => 'الغربية_طنطا', 'name' => 'زفتى'],
            ['city_gov' => 'الغربية_طنطا', 'name' => 'السنطة'],
            ['city_gov' => 'المنوفية_شبين الكوم', 'name' => 'شبين الكوم المركز'],
            ['city_gov' => 'المنوفية_شبين الكوم', 'name' => 'منوف'],
            ['city_gov' => 'المنوفية_شبين الكوم', 'name' => 'السادات'],
            ['city_gov' => 'المنوفية_شبين الكوم', 'name' => 'أشمون'],
            ['city_gov' => 'المنوفية_شبين الكوم', 'name' => 'الباجور'],
            ['city_gov' => 'بني سويف_بني سويف', 'name' => 'بني سويف المركز'],
            ['city_gov' => 'بني سويف_بني سويف', 'name' => 'الواسطى'],
            ['city_gov' => 'بني سويف_بني سويف', 'name' => 'ناصج'],
            ['city_gov' => 'بني سويف_بني سويف', 'name' => 'إهناسيا'],
            ['city_gov' => 'بني سويف_بني سويف', 'name' => 'ببا'],
            ['city_gov' => 'بني سويف_بني سويف', 'name' => 'سمسطا'],
            ['city_gov' => 'الفيوم_الفيوم', 'name' => 'الفيوم المركز'],
            ['city_gov' => 'الفيوم_الفيوم', 'name' => 'الفيوم الجديدة'],
            ['city_gov' => 'الفيوم_الفيوم', 'name' => 'طامية'],
            ['city_gov' => 'الفيوم_الفيوم', 'name' => 'سنورس'],
            ['city_gov' => 'الفيوم_الفيوم', 'name' => 'إطسا'],
            ['city_gov' => 'المنيا_المنيا', 'name' => 'المنيا المركز'],
            ['city_gov' => 'المنيا_المنيا', 'name' => 'المنيا الجديدة'],
            ['city_gov' => 'المنيا_المنيا', 'name' => 'مغاغة'],
            ['city_gov' => 'المنيا_المنيا', 'name' => 'بني مزار'],
            ['city_gov' => 'المنيا_المنيا', 'name' => 'melawi'],
            ['city_gov' => 'المنيا_المنيا', 'name' => 'أبو تيج'],
            ['city_gov' => 'المنيا_المنيا', 'name' => 'دير مواس'],
            ['city_gov' => 'أسيوط_أسيوط', 'name' => 'أسيوط المركز'],
            ['city_gov' => 'أسيوط_أسيوط', 'name' => 'أسيوط الجديدة'],
            ['city_gov' => 'أسيوط_أسيوط', 'name' => 'ال新华村'],
            ['city_gov' => 'أسيوط_أسيوط', 'name' => 'القوصية'],
            ['city_gov' => 'أسيوط_أسيوط', 'name' => 'منفلوط'],
            ['city_gov' => 'أسيوط_أسيوط', 'name' => 'أبو تيج'],
            ['city_gov' => 'أسيوط_أسيوط', 'name' => 'صدفا'],
            ['city_gov' => 'سوهاج_سوهاج', 'name' => 'سوهاج المركز'],
            ['city_gov' => 'سوهاج_سوهاج', 'name' => 'سوهاج الجديدة'],
            ['city_gov' => 'سوهاج_سوهاج', 'name' => 'أخميم'],
            ['city_gov' => 'سوهاج_سوهاج', 'name' => 'EL BALINA'],
            ['city_gov' => 'سوهاج_سوهاج', 'name' => 'جهينة'],
            ['city_gov' => 'سوهاج_سوهاج', 'name' => 'المراغة'],
            ['city_gov' => 'سوهاج_سوهاج', 'name' => 'طما'],
            ['city_gov' => 'قنا_قنا', 'name' => 'قنا المركز'],
            ['city_gov' => 'قنا_قنا', 'name' => 'قنا الجديدة'],
            ['city_gov' => 'قنا_قنا', 'name' => 'الأقصر'],
            ['city_gov' => 'قنا_قنا', 'name' => 'EL BALINA'],
            ['city_gov' => 'قنا_قنا', 'name' => 'نجع حمادي'],
            ['city_gov' => 'قنا_قنا', 'name' => 'دشنا'],
            ['city_gov' => 'قنا_قنا', 'name' => 'فوكة'],
            ['city_gov' => 'الأقصر_الأقصر', 'name' => 'الأقصر المركز'],
            ['city_gov' => 'الأقصر_الأقصر', 'name' => 'الأقصر الجديدة'],
            ['city_gov' => 'الأقصر_الأقصر', 'name' => 'اليرموك'],
            ['city_gov' => 'الأقصر_الأقصر', 'name' => 'البياضية'],
            ['city_gov' => 'الأقصر_الأقصر', 'name' => 'طيبة'],
            ['city_gov' => 'أسوان_أسوان', 'name' => 'أسوان المركز'],
            ['city_gov' => 'أسوان_أسوان', 'name' => 'أسوان الجديدة'],
            ['city_gov' => 'أسوان_أسوان', 'name' => 'دراو'],
            ['city_gov' => 'أسوان_أسوان', 'name' => 'كوم أمبو'],
            ['city_gov' => 'أسوان_أسوان', 'name' => 'نصر النوبة'],
            ['city_gov' => 'البحر الأحمر_الغردقة', 'name' => 'الغردقة المركز'],
            ['city_gov' => 'البحر الأحمر_الغردقة', 'name' => 'الغردقة الجديدة'],
            ['city_gov' => 'البحر الأحمر_الغردقة', 'name' => 'الجونة'],
            ['city_gov' => 'البحر الأحمر_الغردقة', 'name' => 'مرسى علم'],
            ['city_gov' => 'الوادي الجديد_الخارجة', 'name' => 'الخارجة المركز'],
            ['city_gov' => 'الوادي الجديد_الخارجة', 'name' => 'الد淋ة'],
            ['city_gov' => 'الوادي الجديد_الخارجة', 'name' => 'الفرافرة'],
            ['city_gov' => 'مطروح_مطروح', 'name' => 'مطروح المركز'],
            ['city_gov' => 'مطروح_مطروح', 'name' => 'الحمام'],
            ['city_gov' => 'مطروح_مطروح', 'name' => 'العلمين'],
            ['city_gov' => 'مطروح_مطروح', 'name' => 'سيدي براني'],
            ['city_gov' => 'شمال سيناء_العريش', 'name' => 'العريش المركز'],
            ['city_gov' => 'شمال سيناء_العريش', 'name' => 'رفح'],
            ['city_gov' => 'شمال سيناء_العريش', 'name' => 'بئر العبد'],
            ['city_gov' => 'جنوب سيناء_شرم الشيخ', 'name' => 'شرم الشيخ المركز'],
            ['city_gov' => 'جنوب سيناء_شرم الشيخ', 'name' => 'دهب'],
            ['city_gov' => 'جنوب سيناء_شرم الشيخ', 'name' => 'سانت كاترين'],
            ['city_gov' => 'بورسعيد_بورسعيد', 'name' => 'بورسعيد المركز'],
            ['city_gov' => 'بورسعيد_بورسعيد', 'name' => 'بورسعيد الجديدة'],
            ['city_gov' => 'السويس_السويس', 'name' => 'السويس المركز'],
            ['city_gov' => 'السويس_السويس', 'name' => 'عتاقة'],
            ['city_gov' => 'الإسماعيلية_الإسماعيلية', 'name' => 'الإسماعيلية المركز'],
            ['city_gov' => 'الإسماعيلية_الإسماعيلية', 'name' => 'الإسماعيلية الجديدة'],
            ['city_gov' => 'الإسماعيلية_الإسماعيلية', 'name' => 'القنطرة شرق'],
            ['city_gov' => 'الإسماعيلية_الإسماعيلية', 'name' => 'القنطرة غرب'],
            ['city_gov' => 'دمياط_دمياط', 'name' => 'دمياط المركز'],
            ['city_gov' => 'دمياط_دمياط', 'name' => 'دمياط الجديدة'],
            ['city_gov' => 'دمياط_دمياط', 'name' => 'الروضة'],
            ['city_gov' => 'دمياط_دمياط', 'name' => 'فارسكور'],
            ['city_gov' => 'الإسكندرية_العامرية', 'name' => 'العامرية المركز'],
            ['city_gov' => 'الإسكندرية_العامرية', 'name' => 'العجمي'],
        ];

        $districtCount = 0;
        foreach ($districtsData as $district) {
            $cityId = $cityModels[$district['city_gov']]->id;
            District::updateOrCreate(
                ['name' => $district['name'], 'city_id' => $cityId],
                []
            );
            $districtCount++;
        }

        $this->command->info('Geography seeded successfully!');
        $this->command->info('Countries: ' . Country::count());
        $this->command->info('Governorates: ' . Governorate::count());
        $this->command->info('Cities: ' . City::count());
        $this->command->info('Districts: ' . District::count());
    }
}
