<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::statement('PRAGMA foreign_keys = OFF');

        $tables = [
            // === المبيعات ===
            'sales_invoices',
            'sales_invoice_items',
            'sales_invoice_discounts',
            'sales_invoice_taxes',
            'sales_invoice_incentives',
            'sales_incentives',
            'sales_incentive_conditions',
            'sales_incentive_condition_items',
            'sales_incentive_rewards',
            'collections',
            'customer_returns',
            'customer_return_items',

            // === العملاء ===
            'customers',
            'customer_addresses',
            'customer_contacts',
            'customer_credit_limits',
            'customer_groups',
            'customer_classes',
            'customer_types',
            'customer_account_types',
            'customer_ledger',
            'customer_price_levels',
            'customer_special_prices',
            'customer_visits',
            'customer_agreements',
            'customer_agreement_items',
            'customer_agreement_types',
            'customer_agreement_targets',
            'customer_agreement_payments',
            'customer_agreement_history',
            'customer_marketing_supports',
            'customer_rebate_rules',
            'customer_marketing_assets',
            'customer_marketing_materials',
            'customer_tax_profiles',
            'customer_price_lists',

            // === طلبات التحميل ===
            'load_requests',
            'load_request_items',
            'issue_orders',
            'issue_order_items',

            // === الارتجاع ===
            'return_orders',
            'return_order_items',
            'return_authorizations',
            'return_authorization_items',

            // === المندوبين ===
            'salesman_assignments',
            'salesman_settlements',
            'salesman_accounts',
            'salesman_account_movements',
            'salesman_debts',
            'salesman_debt_payment_lines',

            // === خطوط السير ===
            'routes',
            'route_schedules',
            'route_customers',
            'route_visits',
            'route_points',
            'route_assignments',
            'daily_routes',
            'daily_route_customers',
            'route_events',
            'route_templates',
            'route_stops',
            'representatives',

            // === خطط التوزيع ===
            'distribution_plans',
            'distribution_plan_items',
            'distribution_plan_customers',
            'distribution_plan_reps',
            'distribution_plan_products',

            // === المشتريات ===
            'purchase_invoices',
            'purchase_invoice_items',
            'purchase_returns',
            'purchase_return_items',
            'purchase_expenses',
            'purchase_requests',
            'purchase_request_items',
            'purchase_orders',
            'purchase_order_items',
            'purchase_receipts',
            'purchase_receipt_items',
            'suppliers',
            'supplier_groups',
            'supplier_contacts',
            'supplier_quotations',
            'supplier_quotation_items',
            'supplier_ledger',
            'supplier_tax_profiles',

            // === المخزون ===
            'inventory_transactions',
            'inventory_transaction_items',
            'inventory_transaction_types',
            'inventory_opening_balances',
            'inventory_revaluations',
            'inventory_revaluation_items',
            'item_batches',
            'stock_adjustments',
            'stock_adjustment_items',
            'stock_counts',
            'stock_count_items',
            'warehouse_transfers',
            'warehouse_transfer_items',
            'rep_item_distributions',

            // === الأصناف ===
            'items',
            'item_units',
            'item_prices',
            'item_barcodes',
            'item_categories',
            'item_sub_categories',
            'product_companies',
            'units',
            'price_lists',
            'price_levels',
            'pricing_rules',
            'pricing_rule_conditions',
            'pricing_rule_items',
            'pricing_calculations',
            'pricing_calculation_details',
            'pricing_exceptions',
            'pricing_audit_log',
            'quantity_price_breaks',
            'contract_prices',
            'price_approval_requests',
            'price_approval_steps',
            'promotions',
            'promotion_execution_logs',
            'promotion_priorities',
            'promotion_exclusions',

            // === الخزينة ===
            'treasury_transactions',
            'treasury_shifts',
            'treasury_shift_transactions',
            'treasury_counts',
            'treasury_count_details',
            'treasury_transfers',
            'treasury_adjustments',
            'treasury_opening_balances',
            'treasury_daily_closings',
            'treasury_closing_details',
            'treasury_custodies',
            'treasury_custody_transactions',
            'treasury_cash_limits',
            'treasury_alerts',

            // === المحاسبة ===
            'journal_entries',
            'journal_entry_lines',
            'manual_journal_entries',
            'manual_journal_entry_lines',
            'receipt_vouchers',
            'payment_vouchers',
            'opening_balances',
            'opening_balance_documents',
            'opening_balance_document_lines',
            'accounts',
            'account_groups',
            'account_types',
            'fiscal_years',
            'accounting_periods',
            'bank_accounts',
            'bank_transfers',
            'bank_reconciliations',

            // === المخازن ===
            'warehouses',
            'warehouse_types',
            'vehicles',
            'vehicle_types',
            'vehicle_assignments',
            'vehicle_fuel_transactions',
            'vehicle_maintenance',
            'vehicle_loadings',
            'vehicle_loads',
            'vehicle_load_items',
            'vehicle_unloads',
            'vehicle_unload_items',
            'vehicle_warehouses',
            'vehicle_inventory_transactions',
            'vehicle_inventory_transaction_items',
            'vehicle_stock_balances',
            'vehicle_cash_accounts',
            'vehicle_cash_transactions',
            'vehicle_daily_expenses',
            'vehicle_stock_counts',
            'vehicle_stock_count_items',
            'vehicle_settlements',
            'vehicle_settlement_items',
            'vehicle_deposits',
            'vehicle_documents',
            'vehicle_ownership_history',
            'vehicle_meter_readings',
            'vehicle_maintenance_plans',
            'vehicle_work_orders',
            'vehicle_work_order_items',
            'vehicle_maintenance_parts',
            'vehicle_tires',
            'vehicle_tire_movements',
            'vehicle_tire_inspections',
            'vehicle_batteries',
            'vehicle_fuel_cards',
            'vehicle_fuel_stations',
            'vehicle_fuel_prices',
            'vehicle_accidents',
            'vehicle_insurance',
            'vehicle_insurance_claims',
            'vehicle_reservations',
            'vehicle_alerts',
            'vehicle_geofence_events',
            'vehicle_speed_violations',
            'vehicle_idle_time',
            'vehicle_trip_history',
            'vehicle_cost_analysis',
            'drivers',
            'driver_licenses',
            'driver_training',
            'driver_violations',
            'driver_medical_tests',
            'driver_behavior_scores',
            'geofences',

            // === التوزيع اليومي ===
            'daily_distribution_dashboards',

            // === التسويق ===
            'marketing_campaigns',
            'marketing_campaign_customers',
            'marketing_assets',
            'marketing_asset_movements',
            'marketing_asset_maintenance',
            'marketing_materials',
            'marketing_asset_categories',
            'merchandising_visits',
            'merchandising_checklists',
            'merchandising_visit_details',
            'merchandising_photos',
            'merchandising_standards',
            'merchandising_standard_items',
            'merchandising_audits',
            'merchandising_audit_details',
            'merchandising_audit_photos',
            'merchandising_tasks',
            'merchandising_task_assignments',
            'merchandising_task',
            'display_locations',
            'shelf_audits',
            'shelf_audit_items',
            'shelf_share_surveys',
            'shelf_share_items',
            'competitors',
            'competitor_brands',
            'competitor_products',
            'competitor_price_surveys',
            'competitor_price_survey_items',
            'competitor_promotions',
            'competitor_promotion_items',
            'competitor_new_products',
            'competitor_photos',
            'market_issues',
            'surveys',
            'survey_categories',
            'survey_questions',
            'survey_question_options',
            'survey_question_rules',
            'survey_responses',
            'survey_response_answers',
            'survey_response_options',
            'survey_response_photos',
            'survey_scoring_rules',
            'survey_scores',
            'survey_assignments',

            // === الموارد البشرية ===
            'employees',
            'employee_assignments',
            'employee_contracts',
            'employee_contract_amendments',
            'employee_loans',
            'employee_advances',
            'employee_penalties',
            'employee_rewards',
            'employee_missions',
            'employee_shifts',
            'employee_salary_structures',
            'attendance_records',
            'attendance_adjustments',
            'leave_requests',
            'payroll_runs',
            'payroll_run_details',

            // === الإشعارات ===
            'notifications',
            'notification_templates',
            'notification_types',
            'notification_channels',
            'notification_events',
            'notification_rules',
            'notification_rule_recipients',
            'notification_queue',
            'notification_recipients',
            'notification_deliveries',
            'notification_preferences',
            'notification_groups',
            'notification_group_members',
            'alert_rules',
            'alerts',
            'alert_actions',
            'scheduled_notifications',

            // === سجلات ===
            'audit_logs',
            'login_logs',
            'api_logs',
            'api_request_logs',
            'api_rate_limits',
            'api_clients',
            'api_tokens',
            'api_permissions',
            'api_audit_logs',

            // === أصول ===
            'assets',
            'asset_categories',
            'asset_assignments',
            'asset_depreciations',

            // === عملاء潜在 ===
            'leads',
            'lead_activities',
            'opportunities',
            'opportunity_stages',

            // === مستندات ===
            'documents',
            'document_categories',
            'external_documents',
            'external_document_logs',

            // === مزامنة ===
            'sync_batches',
            'sync_logs',
            'mobile_devices',

            // === أجهزة ===
            'devices',

            // === أflows ===
            'workflow_definitions',
            'workflow_steps',
            'approval_requests',
            'approval_actions',
            'workflow_types',
            'workflows',
            'workflow_conditions',
            'workflow_instances',
            'workflow_instance_steps',
            'workflow_delegations',
            'workflow_escalations',
            'workflow_notifications',
            'workflow_actions_log',
            'workflow_templates',
            'workflow_template_steps',
            'workflow_roles',
            'workflow_sla_rules',

            // === التكامل ===
            'integration_providers',
            'integration_accounts',
            'integration_endpoints',
            'integration_events',
            'integration_event_subscriptions',
            'webhook_endpoints',
            'webhook_subscriptions',
            'webhook_logs',
            'integration_jobs',
            'integration_job_runs',
            'integration_error_logs',

            // === أخرى ===
            'gps_tracking_sessions',
            'gps_tracking_points',
            'e_invoice_providers',
            'e_invoice_transactions',
            'message_templates',
            'message_logs',
            'number_series',
            'dashboard_widgets',
            'role_widgets',
            'plan_modules',
            'plan_permissions',
            'plan_limits',
            'features',
            'plan_features',
            'company_settings',
            'modules',
            'report_definitions',
            'kpi_definitions',
            'kpi_targets',
            'kpi_results',
            'sales_targets',
            'sales_targets_details',
            'budgets',
            'budget_lines',
            'demand_forecasts',
            'forecast_history',
            'replenishment_rules',
            'replenishment_suggestions',
            'tax_types',
            'tax_rates',
            'tax_groups',
            'tax_group_details',
            'tax_exemptions',
            'tax_rules',
            'tax_calculations',
            'tax_calculation_details',
            'tax_jurisdictions',
            'tax_periods',
            'tax_returns',
            'tax_return_details',
            'withholding_tax_certificates',
            'pricing_methods',
            'master_data_request_types',
            'master_data_requests',
            'master_data_request_steps',
            'master_data_request_history',
            'master_data_workflows',
            'master_data_workflow_steps',
        ];

        foreach ($tables as $table) {
            if (DB::getSchemaBuilder()->hasTable($table)) {
                DB::table($table)->truncate();
            }
        }

        DB::statement('PRAGMA foreign_keys = ON');
    }

    public function down(): void
    {
        // لا يمكن التراجع عن هذا الحذف
    }
};
