<?php
return [
    'items' => [
        [
            'key' => 'dashboard',
            'feature' => null,
            'permission' => 'dashboard.view',
            'title_en' => 'Dashboard',
            'title_ar' => 'لوحة التحكم',
            'icon' => 'dashboard',
            'color' => '#3B82F6',
            'order' => 0,
            'children' => [],
        ],
        [
            'key' => 'customers',
            'feature' => 'customers',
            'permission' => 'customer.customer.view',
            'title_en' => 'Customers',
            'title_ar' => 'العملاء',
            'icon' => 'people',
            'color' => '#3B82F6',
            'order' => 1,
            'children' => [
                ['key' => 'customers_list', 'feature' => 'customers', 'permission' => 'customer.customer.view', 'title_en' => 'Customers List', 'title_ar' => 'قائمة العملاء', 'icon' => 'people', 'color' => '#3B82F6', 'order' => 1],
                ['key' => 'customer_groups', 'feature' => 'customers', 'permission' => 'customer.group.view', 'title_en' => 'Customer Groups', 'title_ar' => 'مجموعات العملاء', 'icon' => 'group', 'color' => '#8B5CF6', 'order' => 2],
                ['key' => 'customer_types', 'feature' => 'customers', 'permission' => 'customer.type.view', 'title_en' => 'Customer Types', 'title_ar' => 'أنواع العملاء', 'icon' => 'category', 'color' => '#EC4899', 'order' => 3],
                ['key' => 'customer_classes', 'feature' => 'customers', 'permission' => 'customer.class.view', 'title_en' => 'Customer Classes', 'title_ar' => 'تصنيفات العملاء', 'icon' => 'label', 'color' => '#F97316', 'order' => 4],
                ['key' => 'customer_statement', 'feature' => 'customers', 'permission' => 'customer.customer.view', 'title_en' => 'Customer Statement', 'title_ar' => 'كشف حساب العميل', 'icon' => 'receipt_long', 'color' => '#06B6D4', 'order' => 5],
                ['key' => 'customer_payments', 'feature' => 'customers', 'permission' => 'customer.customer.view', 'title_en' => 'Customer Payments', 'title_ar' => 'سداد العملاء', 'icon' => 'payments', 'color' => '#10B981', 'order' => 6],
            ],
        ],
        [
            'key' => 'suppliers',
            'feature' => 'suppliers',
            'permission' => 'purchase.supplier.view',
            'title_en' => 'Suppliers',
            'title_ar' => 'الموردين',
            'icon' => 'local_shipping',
            'color' => '#10B981',
            'order' => 2,
            'children' => [
                ['key' => 'suppliers_list', 'feature' => 'suppliers', 'permission' => 'purchase.supplier.view', 'title_en' => 'Suppliers List', 'title_ar' => 'قائمة الموردين', 'icon' => 'local_shipping', 'color' => '#10B981', 'order' => 1],
                ['key' => 'supplier_groups', 'feature' => 'suppliers', 'permission' => 'supplier.group.view', 'title_en' => 'Supplier Groups', 'title_ar' => 'مجموعات الموردين', 'icon' => 'group', 'color' => '#06B6D4', 'order' => 2],
                ['key' => 'supplier_statement', 'feature' => 'suppliers', 'permission' => 'purchase.supplier.statement', 'title_en' => 'Account Statement', 'title_ar' => 'كشف حساب', 'icon' => 'receipt_long', 'color' => '#F59E0B', 'order' => 3],
            ],
        ],
        [
            'key' => 'items',
            'feature' => 'items',
            'permission' => 'inventory.item.view',
            'title_en' => 'Items & Inventory',
            'title_ar' => 'الأصناف والمخزون',
            'icon' => 'inventory_2',
            'color' => '#F59E0B',
            'order' => 3,
            'children' => [
                ['key' => 'items_list', 'feature' => 'items', 'permission' => 'inventory.item.view', 'title_en' => 'Items List', 'title_ar' => 'قائمة الأصناف', 'icon' => 'inventory_2', 'color' => '#F59E0B', 'order' => 1],
                ['key' => 'categories', 'feature' => 'items', 'permission' => 'inventory.category.view', 'title_en' => 'Categories', 'title_ar' => 'التصنيفات', 'icon' => 'category', 'color' => '#EF4444', 'order' => 2],
                ['key' => 'sub_categories', 'feature' => 'item_sub_categories', 'permission' => 'inventory.sub_category.view', 'title_en' => 'Sub Categories', 'title_ar' => 'التصنيفات الفرعية', 'icon' => 'subdirectory_arrow_right', 'color' => '#EC4899', 'order' => 3],
                ['key' => 'product_companies', 'feature' => 'items', 'permission' => 'inventory.brand.view', 'title_en' => 'Product Companies', 'title_ar' => 'شركات المنتج', 'icon' => 'business', 'color' => '#06B6D4', 'order' => 4],
                ['key' => 'units', 'feature' => 'items', 'permission' => 'inventory.unit.view', 'title_en' => 'Units', 'title_ar' => 'الوحدات', 'icon' => 'straighten', 'color' => '#8B5CF6', 'order' => 5],
                ['key' => 'price_lists', 'feature' => 'items', 'permission' => 'inventory.pricelist.view', 'title_en' => 'Price Lists', 'title_ar' => 'قوائم الأسعار', 'icon' => 'price_change', 'color' => '#06B6D4', 'order' => 6],
            ],
        ],
        [
            'key' => 'sales',
            'feature' => 'sales',
            'permission' => 'sales.invoice.view',
            'title_en' => 'Sales',
            'title_ar' => 'المبيعات',
            'icon' => 'point_of_sale',
            'color' => '#3B82F6',
            'order' => 4,
            'children' => [
                ['key' => 'sales_invoices', 'feature' => 'sales', 'permission' => 'sales.invoice.view', 'title_en' => 'Sales Invoices', 'title_ar' => 'فواتير المبيعات', 'icon' => 'receipt', 'color' => '#3B82F6', 'order' => 1],
                ['key' => 'collections', 'feature' => 'collections', 'permission' => 'collection.view', 'title_en' => 'Collections', 'title_ar' => 'التحصيل', 'icon' => 'payments', 'color' => '#10B981', 'order' => 2],
                ['key' => 'customer_returns', 'feature' => 'sales', 'permission' => 'sales.return.view', 'title_en' => 'Customer Returns', 'title_ar' => 'مرتجعات العملاء', 'icon' => 'replay', 'color' => '#F59E0B', 'order' => 3],
                ['key' => 'pos', 'feature' => 'sales', 'permission' => 'sales.invoice.create', 'title_en' => 'POS', 'title_ar' => 'نقطة البيع', 'icon' => 'point_of_sale', 'color' => '#8B5CF6', 'order' => 4],
                ['key' => 'sales_invoice_new', 'feature' => 'sales', 'permission' => 'sales.invoice.create', 'title_en' => 'New Invoice', 'title_ar' => 'فاتورة مبيعات', 'icon' => 'add_shopping_cart', 'color' => '#22C55E', 'order' => 5],
                ['key' => 'old_sales_screen', 'feature' => 'sales', 'permission' => 'sales.invoice.view', 'title_en' => 'Old Sales Screen', 'title_ar' => 'شاشة المبيعات القديمة', 'icon' => 'receipt_long', 'color' => '#F97316', 'order' => 6],
            ],
        ],
        [
            'key' => 'sales_rep_returns',
            'feature' => 'sales',
            'permission' => 'sales.invoice.view',
            'title_en' => 'Sales Rep Returns',
            'title_ar' => 'عودة المندوبين',
            'icon' => 'assignment_return',
            'color' => '#F59E0B',
            'order' => 4,
            'children' => [
                ['key' => 'sales_rep_returns', 'feature' => 'sales', 'permission' => 'sales.invoice.view', 'title_en' => 'Sales Rep Returns', 'title_ar' => 'عودة المندوبين', 'icon' => 'assignment_return', 'color' => '#F59E0B', 'order' => 1],
            ],
        ],
        [
            'key' => 'route_lines',
            'feature' => null,
            'permission' => null,
            'title_en' => 'Route Lines',
            'title_ar' => 'خطوط السير',
            'icon' => 'route',
            'color' => '#059669',
            'order' => 5,
            'children' => [
                ['key' => 'sales_territories', 'feature' => 'sales', 'permission' => 'sales.invoice.view', 'title_en' => 'Sales Territories', 'title_ar' => 'المناطق البيعية', 'icon' => 'map', 'color' => '#EC4899', 'order' => 1],
                ['key' => 'salesman_assignments', 'feature' => 'sales', 'permission' => 'sales.invoice.view', 'title_en' => 'Salesman Assignments', 'title_ar' => 'ربط المندوبين', 'icon' => 'assignment_ind', 'color' => '#6366F1', 'order' => 2],
                ['key' => 'route_lines_list', 'feature' => 'sales', 'permission' => 'sales.invoice.view', 'title_en' => 'Route Lines', 'title_ar' => 'خطوط السير', 'icon' => 'route', 'color' => '#059669', 'order' => 3],
                ['key' => 'route_customers', 'feature' => 'sales', 'permission' => 'sales.invoice.view', 'title_en' => 'Route Customers', 'title_ar' => 'ربط العملاء', 'icon' => 'link', 'color' => '#10B981', 'order' => 4],
            ],
        ],
        [
            'key' => 'purchases',
            'feature' => 'purchases',
            'permission' => 'purchase.invoice.view',
            'title_en' => 'Purchases',
            'title_ar' => 'المشتريات',
            'icon' => 'shopping_cart',
            'color' => '#8B5CF6',
            'order' => 5,
            'children' => [
                ['key' => 'purchase_invoices', 'feature' => 'purchases', 'permission' => 'purchase.invoice.view', 'title_en' => 'Purchase Invoices', 'title_ar' => 'فواتير المشتريات', 'icon' => 'receipt_long', 'color' => '#8B5CF6', 'order' => 1],
                ['key' => 'payment_vouchers', 'feature' => 'purchases', 'permission' => 'purchase.payment.view', 'title_en' => 'Payment Vouchers', 'title_ar' => 'سندات الصرف', 'icon' => 'money_off', 'color' => '#EF4444', 'order' => 2],
                ['key' => 'purchase_returns', 'feature' => 'purchases', 'permission' => 'purchase.return.view', 'title_en' => 'Purchase Returns', 'title_ar' => 'مرتجعات المشتريات', 'icon' => 'replay', 'color' => '#F59E0B', 'order' => 3],
            ],
        ],
        [
            'key' => 'warehouse',
            'feature' => 'warehouses',
            'permission' => 'warehouses.view',
            'title_en' => 'Warehouse',
            'title_ar' => 'المخازن',
            'icon' => 'warehouse',
            'color' => '#06B6D4',
            'order' => 6,
            'children' => [
                ['key' => 'warehouses', 'feature' => 'warehouses', 'permission' => 'warehouses.view', 'title_en' => 'Warehouses', 'title_ar' => 'المخازن', 'icon' => 'warehouse', 'color' => '#06B6D4', 'order' => 1],
                ['key' => 'stock_balances', 'feature' => 'warehouses', 'permission' => 'reports.stock_balance.view', 'title_en' => 'Stock Balances', 'title_ar' => 'أرصدة المخزون', 'icon' => 'inventory_2', 'color' => '#10B981', 'order' => 2],
                ['key' => 'stock_movements', 'feature' => 'warehouses', 'permission' => 'warehouses.manage', 'title_en' => 'Stock Movements', 'title_ar' => 'حركة المخزون', 'icon' => 'move_up', 'color' => '#F59E0B', 'order' => 3],
            ],
        ],
        [
            'key' => 'load_requests',
            'feature' => null,
            'permission' => 'distribution.load_request.view',
            'title_en' => 'Load Requests',
            'title_ar' => 'أوامر التحميل',
            'icon' => 'local_shipping',
            'color' => '#F59E0B',
            'order' => 7,
            'children' => [
                ['key' => 'load_requests_list', 'feature' => null, 'permission' => 'distribution.load_request.view', 'title_en' => 'Load Requests', 'title_ar' => 'أوامر التحميل', 'icon' => 'local_shipping', 'color' => '#F59E0B', 'order' => 1],
            ],
        ],
        [
            'key' => 'treasury',
            'feature' => 'treasury',
            'permission' => 'treasury.treasury.view',
            'title_en' => 'Treasury',
            'title_ar' => 'الخزينة',
            'icon' => 'account_balance_wallet',
            'color' => '#10B981',
            'order' => 8,
            'children' => [
                ['key' => 'treasuries', 'feature' => 'treasury', 'permission' => 'treasury.treasury.view', 'title_en' => 'Treasuries', 'title_ar' => 'الخزائن', 'icon' => 'account_balance_wallet', 'color' => '#10B981', 'order' => 1],
                ['key' => 'treasury_movements', 'feature' => 'treasury', 'permission' => 'treasury.treasury.movements', 'title_en' => 'Treasury Movements', 'title_ar' => 'حركة الخزينة', 'icon' => 'swap_horiz', 'color' => '#3B82F6', 'order' => 2],
                ['key' => 'treasury_transactions', 'feature' => 'treasury', 'permission' => 'treasury.transaction.view', 'title_en' => 'Treasury Transactions', 'title_ar' => 'قيود الخزينة', 'icon' => 'receipt_long', 'color' => '#8B5CF6', 'order' => 3],
                ['key' => 'salesman_debts', 'feature' => 'treasury', 'permission' => 'treasury.treasury.view', 'title_en' => 'Salesman Debts', 'title_ar' => 'مديونية المندوب', 'icon' => 'account_balance_wallet', 'color' => '#EF4444', 'order' => 4],
                ['key' => 'expense_types', 'feature' => 'treasury', 'permission' => 'treasury.treasury.view', 'title_en' => 'Expense Types', 'title_ar' => 'أنواع المصروفات', 'icon' => 'category', 'color' => '#F59E0B', 'order' => 5],
                ['key' => 'expenses', 'feature' => 'treasury', 'permission' => 'treasury.treasury.view', 'title_en' => 'Expenses', 'title_ar' => 'المصروفات', 'icon' => 'money_off', 'color' => '#EF4444', 'order' => 6],
            ],
        ],
        [
            'key' => 'banks',
            'feature' => 'banking',
            'permission' => 'banking.bank_account.view',
            'title_en' => 'Banks',
            'title_ar' => 'البنوك',
            'icon' => 'account_balance',
            'color' => '#3B82F6',
            'order' => 9,
            'children' => [
                ['key' => 'bank_accounts', 'feature' => 'banking', 'permission' => 'banking.bank_account.view', 'title_en' => 'Bank Accounts', 'title_ar' => 'حسابات البنوك', 'icon' => 'account_balance', 'color' => '#3B82F6', 'order' => 1],
                ['key' => 'bank_transfers', 'feature' => 'banking', 'permission' => 'banking.bank_transfer.view', 'title_en' => 'Bank Transfers', 'title_ar' => 'التحويلات البنكية', 'icon' => 'swap_horiz', 'color' => '#8B5CF6', 'order' => 2],
                ['key' => 'bank_reconciliations', 'feature' => 'banking', 'permission' => 'banking.bank_reconciliation.view', 'title_en' => 'Bank Reconciliations', 'title_ar' => 'التسويات البنكية', 'icon' => 'fact_check', 'color' => '#10B981', 'order' => 3],
            ],
        ],
        [
            'key' => 'accounting',
            'feature' => 'accounting',
            'permission' => 'accounting.journal.view',
            'title_en' => 'Accounting',
            'title_ar' => 'الحسابات',
            'icon' => 'calculate',
            'color' => '#6366F1',
            'order' => 10,
            'children' => [
                ['key' => 'journal_entries', 'feature' => 'accounting', 'permission' => 'accounting.journal.view', 'title_en' => 'Journal Entries', 'title_ar' => 'القيود اليومية', 'icon' => 'receipt_long', 'color' => '#6366F1', 'order' => 1],
            ],
        ],
        [
            'key' => 'opening_balances',
            'feature' => 'settings',
            'permission' => 'settings.view',
            'title_en' => 'Opening Balances',
            'title_ar' => 'الأرصدة الافتتاحية',
            'icon' => 'balance',
            'color' => '#6366F1',
            'order' => 11,
            'children' => [
                ['key' => 'opening_balance_documents', 'feature' => 'settings', 'permission' => 'settings.view', 'title_en' => 'Opening Balance Documents', 'title_ar' => 'قيود الأرصدة الافتتاحية', 'icon' => 'receipt_long', 'color' => '#6366F1', 'order' => 1],
                ['key' => 'opening_balance_treasury', 'feature' => 'settings', 'permission' => 'settings.view', 'title_en' => 'Treasury Opening Balance', 'title_ar' => 'أرصدة الخزنة الافتتاحية', 'icon' => 'account_balance_wallet', 'color' => '#10B981', 'order' => 2],
                ['key' => 'opening_balance_bank', 'feature' => 'settings', 'permission' => 'settings.view', 'title_en' => 'Bank Opening Balance', 'title_ar' => 'أرصدة البنك الافتتاحية', 'icon' => 'account_balance', 'color' => '#3B82F6', 'order' => 3],
                ['key' => 'opening_balance_products', 'feature' => 'settings', 'permission' => 'settings.view', 'title_en' => 'Products Opening Balance', 'title_ar' => 'أرصدة المنتجات الافتتاحية', 'icon' => 'inventory_2', 'color' => '#8B5CF6', 'order' => 4],
                ['key' => 'opening_balance_suppliers', 'feature' => 'settings', 'permission' => 'settings.view', 'title_en' => 'Suppliers Opening Balance', 'title_ar' => 'أرصدة الموردين الافتتاحية', 'icon' => 'local_shipping', 'color' => '#F59E0B', 'order' => 5],
            ],
        ],
        [
            'key' => 'settings',
            'feature' => 'settings',
            'permission' => 'settings.view',
            'title_en' => 'Settings',
            'title_ar' => 'الإعدادات',
            'icon' => 'settings',
            'color' => '#F59E0B',
            'order' => 12,
            'children' => [
                ['key' => 'company_settings', 'feature' => 'settings', 'permission' => 'settings.view', 'title_en' => 'Company Settings', 'title_ar' => 'إعدادات الشركة', 'icon' => 'business', 'color' => '#F59E0B', 'order' => 1],
                ['key' => 'companies_list', 'feature' => 'multi_company', 'permission' => 'settings.company.view', 'title_en' => 'Companies', 'title_ar' => 'الشركات', 'icon' => 'business_center', 'color' => '#3B82F6', 'order' => 2],
                ['key' => 'branches', 'feature' => 'settings', 'permission' => 'settings.branch.view', 'title_en' => 'Branches', 'title_ar' => 'الفروع', 'icon' => 'account_tree', 'color' => '#10B981', 'order' => 3],
                ['key' => 'locations', 'feature' => 'settings', 'permission' => 'settings.view', 'title_en' => 'Locations', 'title_ar' => 'المواقع', 'icon' => 'public', 'color' => '#8B5CF6', 'order' => 4],
                ['key' => 'users', 'feature' => 'settings', 'permission' => 'settings.user.view', 'title_en' => 'Users', 'title_ar' => 'المستخدمين', 'icon' => 'people', 'color' => '#06B6D4', 'order' => 5],
                ['key' => 'roles_list', 'feature' => 'settings', 'permission' => 'settings.role.view', 'title_en' => 'Roles Management', 'title_ar' => 'إدارة الأدوار', 'icon' => 'admin_panel_settings', 'color' => '#7C3AED', 'order' => 6],
                ['key' => 'permission_matrix', 'feature' => 'settings', 'permission' => 'settings.role.assign_permissions', 'title_en' => 'Permission Matrix', 'title_ar' => 'مصفوفة الصلاحيات', 'icon' => 'grid_on', 'color' => '#3B82F6', 'order' => 7],
                ['key' => 'company_sidebar_management', 'feature' => 'settings', 'permission' => 'settings.view', 'title_en' => 'Sidebar Management', 'title_ar' => 'إدارة السايد بار للشركات', 'icon' => 'view_sidebar', 'color' => '#8B5CF6', 'order' => 8],
            ],
        ],
        [
            'key' => 'reports',
            'feature' => 'reports',
            'permission' => 'reports.view',
            'title_en' => 'Reports',
            'title_ar' => 'التقارير',
            'icon' => 'analytics',
            'color' => '#06B6D4',
            'order' => 13,
            'children' => [
                ['key' => 'report_sales', 'feature' => 'reports', 'permission' => 'reports.sales.view', 'title_en' => 'Sales Report', 'title_ar' => 'تقرير المبيعات', 'icon' => 'receipt', 'color' => '#3B82F6', 'order' => 1],
                ['key' => 'report_purchases', 'feature' => 'reports', 'permission' => 'reports.purchases.view', 'title_en' => 'Purchases Report', 'title_ar' => 'تقرير المشتريات', 'icon' => 'receipt_long', 'color' => '#8B5CF6', 'order' => 2],
                ['key' => 'report_inventory', 'feature' => 'reports', 'permission' => 'reports.inventory.view', 'title_en' => 'Inventory Report', 'title_ar' => 'تقرير المخزون', 'icon' => 'inventory_2', 'color' => '#F59E0B', 'order' => 3],
                ['key' => 'report_profit', 'feature' => 'reports', 'permission' => 'reports.profit.view', 'title_en' => 'Profit Report', 'title_ar' => 'تقرير الأرباح', 'icon' => 'trending_up', 'color' => '#10B981', 'order' => 4],
                ['key' => 'report_item_movement', 'feature' => 'reports', 'permission' => 'reports.inventory.view', 'title_en' => 'Item Movement', 'title_ar' => 'تقرير حركة صنف', 'icon' => 'swap_vert', 'color' => '#EC4899', 'order' => 5],
                ['key' => 'report_item_ledger', 'feature' => 'reports', 'permission' => 'reports.inventory.view', 'title_en' => 'Item Ledger', 'title_ar' => 'حركة الصنف (متقدم)', 'icon' => 'account_balance', 'color' => '#8B5CF6', 'order' => 6],
                ['key' => 'report_new_inventory_movement', 'feature' => 'reports', 'permission' => 'reports.inventory.view', 'title_en' => 'New Inventory Movement', 'title_ar' => 'حركة المخزون الجديدة', 'icon' => 'inventory', 'color' => '#14B8A6', 'order' => 7],
                ['key' => 'report_customer_balances', 'feature' => 'reports', 'permission' => 'reports.view', 'title_en' => 'Customer Balances', 'title_ar' => 'أرصدة العملاء', 'icon' => 'people', 'color' => '#3B82F6', 'order' => 8],
                ['key' => 'report_treasury', 'feature' => 'reports', 'permission' => 'reports.view', 'title_en' => 'Treasury Report', 'title_ar' => 'تقرير الخزينة', 'icon' => 'account_balance_wallet', 'color' => '#10B981', 'order' => 9],
                ['key' => 'report_vehicle_expenses', 'feature' => 'reports', 'permission' => 'reports.view', 'title_en' => 'Vehicle Expenses', 'title_ar' => 'مصروفات السيارات', 'icon' => 'directions_car', 'color' => '#F59E0B', 'order' => 10],
                ['key' => 'report_daily_summary', 'feature' => 'reports', 'permission' => 'reports.view', 'title_en' => 'Daily Summary', 'title_ar' => 'الملخص اليومي', 'icon' => 'today', 'color' => '#06B6D4', 'order' => 11],
                ['key' => 'report_hr', 'feature' => 'reports', 'permission' => 'reports.view', 'title_en' => 'HR Reports', 'title_ar' => 'تقارير الموارد البشرية', 'icon' => 'work', 'color' => '#EC4899', 'order' => 12],
                ['key' => 'report_cost_centers', 'feature' => 'reports', 'permission' => 'reports.view', 'title_en' => 'Cost Centers', 'title_ar' => 'مراكز التكلفة', 'icon' => 'account_tree', 'color' => '#8B5CF6', 'order' => 13],
                ['key' => 'report_account_statement', 'feature' => 'reports', 'permission' => 'reports.view', 'title_en' => 'Account Statement', 'title_ar' => 'كشف حساب', 'icon' => 'receipt_long', 'color' => '#6366F1', 'order' => 14],
                ['key' => 'report_profit_loss', 'feature' => 'reports', 'permission' => 'reports.view', 'title_en' => 'Profit & Loss', 'title_ar' => 'الأرباح والخسائر', 'icon' => 'pie_chart', 'color' => '#10B981', 'order' => 15],
                ['key' => 'report_rep_movement', 'feature' => 'reports', 'permission' => 'reports.view', 'title_en' => 'Rep Movement', 'title_ar' => 'حركة المندوب بالصنف', 'icon' => 'person_search', 'color' => '#3B82F6', 'order' => 16],
                ['key' => 'report_rep_stock_balance', 'feature' => 'reports', 'permission' => 'reports.view', 'title_en' => 'Rep Stock Balance', 'title_ar' => 'رصيد المندوب', 'icon' => 'inventory_2', 'color' => '#F59E0B', 'order' => 17],
                ['key' => 'report_warehouse_daily_movement', 'feature' => 'reports', 'permission' => 'reports.inventory.view', 'title_en' => 'Warehouse Daily Movement', 'title_ar' => 'حركة المخزون اليومية', 'icon' => 'warehouse', 'color' => '#F59E0B', 'order' => 18],
                ['key' => 'report_builder', 'feature' => 'reports', 'permission' => 'reports.view', 'title_en' => 'Report Builder', 'title_ar' => 'منشئ التقارير', 'icon' => 'build', 'color' => '#EC4899', 'order' => 19],
            ],
        ],
        [
            'key' => 'fleet',
            'feature' => 'fleet',
            'permission' => 'vehicle.vehicle.view',
            'title_en' => 'Fleet Management',
            'title_ar' => 'إدارة الأسطول',
            'icon' => 'local_shipping',
            'color' => '#F97316',
            'order' => 14,
            'children' => [
                ['key' => 'vehicles_list', 'feature' => 'fleet', 'permission' => 'vehicle.vehicle.view', 'title_en' => 'Vehicles', 'title_ar' => 'المركبات', 'icon' => 'local_shipping', 'color' => '#F97316', 'order' => 1],
                ['key' => 'vehicle_types', 'feature' => 'fleet', 'permission' => 'vehicle.vehicle.view', 'title_en' => 'Vehicle Types', 'title_ar' => 'أنواع المركبات', 'icon' => 'category', 'color' => '#8B5CF6', 'order' => 2],
            ],
        ],
        [
            'key' => 'hr',
            'feature' => null,
            'permission' => 'hr.employee.view',
            'title_en' => 'HR',
            'title_ar' => 'الموارد البشرية',
            'icon' => 'groups',
            'color' => '#EC4899',
            'order' => 15,
            'children' => [
                ['key' => 'departments', 'feature' => null, 'permission' => 'hr.department.view', 'title_en' => 'Departments', 'title_ar' => 'الأقسام', 'icon' => 'account_tree', 'color' => '#8B5CF6', 'order' => 1],
                ['key' => 'job_positions', 'feature' => null, 'permission' => 'hr.job_position.view', 'title_en' => 'Job Positions', 'title_ar' => 'الوظائف', 'icon' => 'engineering', 'color' => '#EC4899', 'order' => 2],
                ['key' => 'job_grades', 'feature' => null, 'permission' => 'hr.job_position.view', 'title_en' => 'Job Grades', 'title_ar' => 'الدرجات الوظيفية', 'icon' => 'stairs', 'color' => '#EC4899', 'order' => 3],
                ['key' => 'leave_types', 'feature' => null, 'permission' => 'hr.leave.view', 'title_en' => 'Leave Types', 'title_ar' => 'أنواع الإجازات', 'icon' => 'event', 'color' => '#EC4899', 'order' => 4],
                ['key' => 'contract_types', 'feature' => null, 'permission' => 'hr.contract.view', 'title_en' => 'Contract Types', 'title_ar' => 'أنواع العقود', 'icon' => 'description', 'color' => '#EC4899', 'order' => 5],
                ['key' => 'contract_statuses', 'feature' => null, 'permission' => 'hr.contract.view', 'title_en' => 'Contract Statuses', 'title_ar' => 'حالات العقود', 'icon' => 'flag', 'color' => '#EC4899', 'order' => 6],
                ['key' => 'salary_components', 'feature' => null, 'permission' => 'hr.salary_component.view', 'title_en' => 'Salary Components', 'title_ar' => 'مكونات الراتب', 'icon' => 'payments', 'color' => '#EC4899', 'order' => 7],
                ['key' => 'employees_list', 'feature' => null, 'permission' => 'hr.employee.view', 'title_en' => 'Employees', 'title_ar' => 'الموظفين', 'icon' => 'people', 'color' => '#10B981', 'order' => 8],
                ['key' => 'attendance', 'feature' => null, 'permission' => 'hr.attendance.view', 'title_en' => 'Attendance', 'title_ar' => 'الحضور والانصراف', 'icon' => 'schedule', 'color' => '#EC4899', 'order' => 9],
                ['key' => 'payroll', 'feature' => null, 'permission' => 'hr.payroll.view', 'title_en' => 'Payroll', 'title_ar' => 'الرواتب', 'icon' => 'payments', 'color' => '#EC4899', 'order' => 10],
                ['key' => 'leave', 'feature' => null, 'permission' => 'hr.leave.view', 'title_en' => 'Leave', 'title_ar' => 'الإجازات', 'icon' => 'event_busy', 'color' => '#EC4899', 'order' => 11],
                ['key' => 'employee_statuses', 'feature' => null, 'permission' => 'hr.employee.view', 'title_en' => 'Employee Statuses', 'title_ar' => 'حالات الموظفين', 'icon' => 'flag', 'color' => '#EC4899', 'order' => 12],
                ['key' => 'salary_scales', 'feature' => null, 'permission' => 'hr.salary_component.view', 'title_en' => 'Salary Scales', 'title_ar' => 'المواصفات الراتبية', 'icon' => 'monetization_on', 'color' => '#EC4899', 'order' => 13],
                ['key' => 'position_levels', 'feature' => null, 'permission' => 'hr.job_position.view', 'title_en' => 'Position Levels', 'title_ar' => 'مستويات الوظائف', 'icon' => 'leaderboard', 'color' => '#EC4899', 'order' => 14],
                ['key' => 'employee_contracts', 'feature' => null, 'permission' => 'hr.contract.view', 'title_en' => 'Employee Contracts', 'title_ar' => 'عقود الموظفين', 'icon' => 'description', 'color' => '#EC4899', 'order' => 15],
                ['key' => 'employee_assignments', 'feature' => null, 'permission' => 'hr.employee.view', 'title_en' => 'Employee Assignments', 'title_ar' => 'تعيينات الموظفين', 'icon' => 'assignment_ind', 'color' => '#EC4899', 'order' => 16],
                ['key' => 'payroll_periods', 'feature' => null, 'permission' => 'hr.payroll.view', 'title_en' => 'Payroll Periods', 'title_ar' => 'فترات الرواتب', 'icon' => 'date_range', 'color' => '#EC4899', 'order' => 17],
                ['key' => 'holidays', 'feature' => null, 'permission' => 'hr.attendance.view', 'title_en' => 'Holidays', 'title_ar' => 'العطل', 'icon' => 'celebration', 'color' => '#EC4899', 'order' => 18],
                ['key' => 'employee_loans', 'feature' => null, 'permission' => 'hr.loan.view', 'title_en' => 'Employee Loans', 'title_ar' => 'قروض الموظفين', 'icon' => 'account_balance', 'color' => '#EC4899', 'order' => 19],
                ['key' => 'employee_advances', 'feature' => null, 'permission' => 'hr.advance.view', 'title_en' => 'Employee Advances', 'title_ar' => 'سلف الموظفين', 'icon' => 'savings', 'color' => '#EC4899', 'order' => 20],
                ['key' => 'employee_penalties', 'feature' => null, 'permission' => 'hr.penalty.view', 'title_en' => 'Employee Penalties', 'title_ar' => 'خصومات الموظفين', 'icon' => 'gavel', 'color' => '#EC4899', 'order' => 21],
                ['key' => 'employee_rewards', 'feature' => null, 'permission' => 'hr.reward.view', 'title_en' => 'Employee Rewards', 'title_ar' => 'مكافآت الموظفين', 'icon' => 'emoji_events', 'color' => '#EC4899', 'order' => 22],
                ['key' => 'employee_missions', 'feature' => null, 'permission' => 'hr.mission.view', 'title_en' => 'Employee Missions', 'title_ar' => 'مهام الموظفين', 'icon' => 'flight', 'color' => '#EC4899', 'order' => 23],
                ['key' => 'shift_types', 'feature' => null, 'permission' => 'hr.shift.view', 'title_en' => 'Shift Types', 'title_ar' => 'أنواع المناوبات', 'icon' => 'more_time', 'color' => '#EC4899', 'order' => 24],
                ['key' => 'shifts', 'feature' => null, 'permission' => 'hr.shift.view', 'title_en' => 'Shifts', 'title_ar' => 'المناوبات', 'icon' => 'access_time', 'color' => '#EC4899', 'order' => 25],
            ],
        ],
        [
            'key' => 'distribution_plans',
            'feature' => null,
            'permission' => 'distribution.route.view',
            'title_en' => 'Distribution Planning',
            'title_ar' => 'التخطيط والتوزيع',
            'icon' => 'pie_chart',
            'color' => '#8B5CF6',
            'order' => 16,
            'children' => [
                ['key' => 'distribution_plans_list', 'feature' => null, 'permission' => 'distribution.route.view', 'title_en' => 'Distribution Plans', 'title_ar' => 'خطط التوزيع', 'icon' => 'pie_chart', 'color' => '#8B5CF6', 'order' => 1],
                ['key' => 'new_distribution_plan_v2', 'feature' => null, 'permission' => 'distribution.route.create', 'title_en' => 'New Distribution Plan', 'title_ar' => 'خطة التوزيع الجديدة', 'icon' => 'add_circle', 'color' => '#10B981', 'order' => 2],
            ],
        ],
        [
            'key' => 'return_orders',
            'feature' => null,
            'permission' => 'sales.return.view',
            'title_en' => 'Return Orders',
            'title_ar' => 'طلبات الارتجاع',
            'icon' => 'assignment_return',
            'color' => '#EF4444',
            'order' => 17,
            'children' => [
                ['key' => 'return_orders_list', 'feature' => null, 'permission' => 'sales.return.view', 'title_en' => 'Return Orders', 'title_ar' => 'طلبات الارتجاع', 'icon' => 'assignment_return', 'color' => '#EF4444', 'order' => 1],
            ],
        ],
        [
            'key' => 'rep_settlements',
            'feature' => null,
            'permission' => 'distribution.salesman.daily_settlement.view',
            'title_en' => 'Rep Settlements',
            'title_ar' => 'تسويات المندوبين',
            'icon' => 'account_balance',
            'color' => '#10B981',
            'order' => 18,
            'children' => [
                ['key' => 'rep_settlements_list', 'feature' => null, 'permission' => 'distribution.salesman.daily_settlement.view', 'title_en' => 'Settlements', 'title_ar' => 'التسويات', 'icon' => 'account_balance', 'color' => '#10B981', 'order' => 1],
                ['key' => 'rep_settlements_pending', 'feature' => null, 'permission' => 'distribution.salesman.daily_settlement.approve', 'title_en' => 'Pending Settlements', 'title_ar' => 'التسويات المعلقة', 'icon' => 'pending_actions', 'color' => '#F59E0B', 'order' => 2],
                ['key' => 'rep_debt_payment', 'feature' => null, 'permission' => 'distribution.salesman.daily_settlement.view', 'title_en' => 'Debt Payment', 'title_ar' => 'سداد مديونيات المندوبين', 'icon' => 'payment', 'color' => '#EF4444', 'order' => 3],
            ],
        ],
        [
            'key' => 'reviews',
            'feature' => null,
            'permission' => 'settings.view',
            'title_en' => 'Screen Review',
            'title_ar' => 'مراجعة الشاشات',
            'icon' => 'fact_check',
            'color' => '#EC4899',
            'order' => 18,
            'children' => [
                ['key' => 'screen_review', 'feature' => null, 'permission' => 'settings.view', 'title_en' => 'Screen Review', 'title_ar' => 'مراجعة الشاشات', 'icon' => 'fact_check', 'color' => '#EC4899', 'order' => 1],
            ],
        ],
        [
            'key' => 'audit',
            'feature' => 'audit_log',
            'permission' => 'audit.log.view',
            'title_en' => 'Audit Log',
            'title_ar' => 'سجل التدقيق',
            'icon' => 'history',
            'color' => '#6366F1',
            'order' => 19,
            'children' => [
                ['key' => 'audit_log', 'feature' => 'audit_log', 'permission' => 'audit.log.view', 'title_en' => 'Audit Log', 'title_ar' => 'سجل التدقيق', 'icon' => 'history', 'color' => '#6366F1', 'order' => 1],
            ],
        ],
        [
            'key' => 'notifications',
            'feature' => 'notifications',
            'permission' => 'notification.log.view',
            'title_en' => 'Notifications',
            'title_ar' => 'الإشعارات',
            'icon' => 'notifications',
            'color' => '#F59E0B',
            'order' => 20,
            'children' => [
                ['key' => 'notifications_list', 'feature' => 'notifications', 'permission' => 'notification.log.view', 'title_en' => 'Notifications', 'title_ar' => 'الإشعارات', 'icon' => 'notifications', 'color' => '#F59E0B', 'order' => 1],
            ],
        ],
        [
            'key' => 'approvals',
            'feature' => 'approval',
            'permission' => 'settings.role.view',
            'title_en' => 'Approvals',
            'title_ar' => 'الموافقات',
            'icon' => 'verified_user',
            'color' => '#10B981',
            'order' => 21,
            'children' => [
                ['key' => 'approvals_list', 'feature' => 'approval', 'permission' => 'settings.role.view', 'title_en' => 'Approvals', 'title_ar' => 'الموافقات', 'icon' => 'verified_user', 'color' => '#10B981', 'order' => 1],
            ],
        ],
        [
            'key' => 'integrations',
            'feature' => null,
            'permission' => 'integration.provider.view',
            'title_en' => 'Integrations',
            'title_ar' => 'التكامل',
            'icon' => 'hub',
            'color' => '#06B6D4',
            'order' => 22,
            'children' => [
                ['key' => 'webhooks', 'feature' => null, 'permission' => 'integration.webhook.view', 'title_en' => 'Webhooks', 'title_ar' => 'Webhooks', 'icon' => 'webhook', 'color' => '#06B6D4', 'order' => 1],
                ['key' => 'api_keys', 'feature' => null, 'permission' => 'integration.api_client.view', 'title_en' => 'API Keys', 'title_ar' => 'مفاتيح API', 'icon' => 'vpn_key', 'color' => '#3B82F6', 'order' => 2],
                ['key' => 'api_logs', 'feature' => null, 'permission' => 'integration.log.view', 'title_en' => 'API Logs', 'title_ar' => 'سجلات API', 'icon' => 'history', 'color' => '#6366F1', 'order' => 3],
            ],
        ],
        [
            'key' => 'monitoring',
            'feature' => null,
            'permission' => 'settings.view',
            'title_en' => 'Monitoring',
            'title_ar' => 'المراقبة',
            'icon' => 'monitor',
            'color' => '#F59E0B',
            'order' => 23,
            'children' => [
                ['key' => 'queue_monitor', 'feature' => null, 'permission' => 'settings.view', 'title_en' => 'Queue Monitor', 'title_ar' => 'مراقبة الطوابير', 'icon' => 'monitor', 'color' => '#F59E0B', 'order' => 1],
                ['key' => 'scheduled_tasks', 'feature' => null, 'permission' => 'settings.view', 'title_en' => 'Scheduled Tasks', 'title_ar' => 'المهام المجدولة', 'icon' => 'schedule', 'color' => '#10B981', 'order' => 2],
                ['key' => 'system_health', 'feature' => null, 'permission' => 'settings.view', 'title_en' => 'System Health', 'title_ar' => 'صحة النظام', 'icon' => 'health_and_safety', 'color' => '#3B82F6', 'order' => 3],
                ['key' => 'activity_logs', 'feature' => null, 'permission' => 'audit.log.view', 'title_en' => 'Activity Logs', 'title_ar' => 'سجل النشاطات', 'icon' => 'history', 'color' => '#6366F1', 'order' => 4],
                ['key' => 'clear_data', 'feature' => null, 'permission' => 'settings.view', 'title_en' => 'Clear Data', 'title_ar' => 'مسح البيانات', 'icon' => 'delete_forever', 'color' => '#EF4444', 'order' => 5],
            ],
        ],
    ],
];
