-- Exported schema from D:\axionyx_erp\database\scripts/../database.sqlite
-- Generated on 2026-06-06 11:40:07

CREATE TABLE "activity_logs" ("id" integer primary key autoincrement not null, "user_id" integer, "action" varchar not null, "table_name" varchar not null, "record_id" integer, "old_values" text, "new_values" text, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, foreign key("user_id") references "users"("id") on delete set null);

CREATE TABLE "admin_modules" ("id" integer primary key autoincrement not null, "key" varchar not null, "title" varchar not null, "icon" varchar, "sort_order" integer not null default '0', "is_active" tinyint(1) not null default '1', "created_at" datetime, "updated_at" datetime, "deleted_at" datetime);

CREATE TABLE "admin_screens" ("id" integer primary key autoincrement not null, "module_id" integer not null, "parent_id" integer, "key" varchar not null, "title" varchar not null, "icon" varchar, "route" varchar not null, "api_resource" varchar, "screen_type" varchar not null default 'list', "sort_order" integer not null default '0', "is_active" tinyint(1) not null default '1', "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, foreign key("module_id") references "admin_modules"("id") on delete cascade, foreign key("parent_id") references "admin_screens"("id") on delete set null);

CREATE TABLE "areas" ("id" integer primary key autoincrement not null, "district_id" integer not null, "name" varchar not null, "is_active" tinyint(1) not null default '1', "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, foreign key("district_id") references "districts"("id") on delete cascade);

CREATE TABLE "attendance_records" ("id" integer primary key autoincrement not null, "employee_id" integer not null, "attendance_date" date not null, "shift_id" integer, "check_in" datetime, "check_out" datetime, "status" varchar not null default 'present', "late_minutes" integer not null default '0', "early_leave_minutes" integer not null default '0', "overtime_minutes" integer not null default '0', "notes" text, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, foreign key("employee_id") references "employees"("id") on delete cascade, foreign key("shift_id") references "work_shifts"("id") on delete set null);

CREATE TABLE "bank_transactions" ("id" integer primary key autoincrement not null, "bank_id" integer not null, "transaction_type" varchar not null, "amount" numeric not null, "reference_type" varchar, "reference_id" integer, "transaction_date" date not null, "notes" text, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, foreign key("bank_id") references "banks"("id") on delete cascade);

CREATE TABLE "banks" ("id" integer primary key autoincrement not null, "name" varchar not null, "account_number" varchar, "iban" varchar, "balance" numeric not null default '0', "created_at" datetime, "updated_at" datetime, "deleted_at" datetime);

CREATE TABLE "bonuses" ("id" integer primary key autoincrement not null, "employee_id" integer not null, "title" varchar not null, "bonus_type" varchar not null default 'other', "amount" numeric not null, "bonus_date" date not null, "status" varchar not null default 'pending', "payroll_run_id" integer, "approved_by" integer, "approved_at" datetime, "notes" text, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, foreign key("employee_id") references "employees"("id") on delete cascade, foreign key("payroll_run_id") references "payroll_runs"("id") on delete set null, foreign key("approved_by") references "users"("id") on delete set null);

CREATE TABLE "cache" ("key" varchar not null, "value" text not null, "expiration" integer not null, primary key ("key"));

CREATE TABLE "cache_locks" ("key" varchar not null, "owner" varchar not null, "expiration" integer not null, primary key ("key"));

CREATE TABLE "cash_transactions" ("id" integer primary key autoincrement not null, "cashbox_id" integer not null, "transaction_type" varchar not null, "amount" numeric not null, "reference_type" varchar, "reference_id" integer, "transaction_date" date not null, "notes" text, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, foreign key("cashbox_id") references "cashboxes"("id") on delete cascade);

CREATE TABLE "cashboxes" ("id" integer primary key autoincrement not null, "name" varchar not null, "balance" numeric not null default '0', "created_at" datetime, "updated_at" datetime, "deleted_at" datetime);

CREATE TABLE "categories" ("id" integer primary key autoincrement not null, "name" varchar not null, "description" text, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime);

CREATE TABLE "customer_payments" ("id" integer primary key autoincrement not null, "customer_id" integer not null, "invoice_id" integer, "payment_date" date not null, "amount" numeric not null, "payment_method" varchar not null, "notes" text, "created_by" integer, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, foreign key("customer_id") references "customers"("id") on delete cascade, foreign key("invoice_id") references "invoices"("id") on delete set null, foreign key("created_by") references "users"("id") on delete set null);

CREATE TABLE "customers" ("id" integer primary key autoincrement not null, "code" varchar not null, "name" varchar not null, "phone" varchar, "mobile" varchar, "email" varchar, "address" text, "latitude" numeric, "longitude" numeric, "representative_id" integer, "credit_limit" numeric not null default ('0'), "current_balance" numeric not null default ('0'), "notes" text, "is_active" tinyint(1) not null default ('1'), "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, "street_id" integer, foreign key("representative_id") references representatives("id") on delete set null on update no action, foreign key("street_id") references "streets"("id") on delete set null);

CREATE TABLE "departments" ("id" integer primary key autoincrement not null, "parent_id" integer, "code" varchar not null, "name" varchar not null, "description" text, "manager_id" integer, "sort_order" integer not null default '0', "is_active" tinyint(1) not null default '1', "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, foreign key("parent_id") references "departments"("id") on delete set null, foreign key("manager_id") references "users"("id") on delete set null);

CREATE TABLE "dispatch_order_items" ("id" integer primary key autoincrement not null, "dispatch_order_id" integer not null, "product_id" integer not null, "quantity" numeric not null, "unit_cost" numeric not null default '0', "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, foreign key("dispatch_order_id") references "dispatch_orders"("id") on delete cascade, foreign key("product_id") references "products"("id") on delete cascade);

CREATE TABLE "dispatch_orders" ("id" integer primary key autoincrement not null, "order_no" varchar not null, "warehouse_id" integer not null, "representative_id" integer not null, "order_date" date not null, "status" varchar check ("status" in ('draft', 'pending', 'approved', 'cancelled')) not null default 'draft', "notes" text, "created_by" integer, "approved_by" integer, "approved_at" datetime, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, foreign key("warehouse_id") references "warehouses"("id") on delete cascade, foreign key("representative_id") references "representatives"("id") on delete cascade, foreign key("created_by") references "users"("id") on delete set null, foreign key("approved_by") references "users"("id") on delete set null);

CREATE TABLE "districts" ("id" integer primary key autoincrement not null, "governorate_id" integer not null, "name" varchar not null, "is_active" tinyint(1) not null default '1', "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, foreign key("governorate_id") references "governorates"("id") on delete cascade);

CREATE TABLE "employee_advances" ("id" integer primary key autoincrement not null, "employee_id" integer not null, "title" varchar not null, "amount" numeric not null, "monthly_installment" numeric not null, "remaining_amount" numeric not null, "advance_date" date not null, "status" varchar not null default 'active', "payroll_run_id" integer, "notes" text, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, foreign key("employee_id") references "employees"("id") on delete cascade, foreign key("payroll_run_id") references "payroll_runs"("id") on delete set null);

CREATE TABLE "employee_salaries" ("id" integer primary key autoincrement not null, "employee_id" integer not null, "basic_salary" numeric not null, "housing_allowance" numeric not null default '0', "transport_allowance" numeric not null default '0', "other_allowances" numeric not null default '0', "social_insurance" numeric not null default '0', "income_tax" numeric not null default '0', "other_deductions" numeric not null default '0', "effective_from" date not null, "effective_to" date, "payment_method" varchar not null default 'bank', "bank_account" varchar, "notes" text, "is_active" tinyint(1) not null default '1', "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, "fuel_allowance" numeric not null default '0', "travel_allowance" numeric not null default '0', "commission_allowance" numeric not null default '0', "mobile_allowance" numeric not null default '0', foreign key("employee_id") references "employees"("id") on delete cascade);

CREATE TABLE "employees" ("id" integer primary key autoincrement not null, "name" varchar not null, "user_id" integer, "employee_code" varchar not null, "department_id" integer, "job_position_id" integer, "manager_id" integer, "hire_date" date, "employment_status" varchar not null default ('active'), "notes" text, "is_active" tinyint(1) not null default ('1'), "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, "employee_type" varchar not null default 'field', "sales_territory_id" integer, "monthly_target_amount" numeric not null default '0', "commission_rate" numeric not null default '0', "vehicle_number" varchar, "fuel_allowance" numeric not null default '0', "travel_allowance" numeric not null default '0', "is_field_staff" tinyint(1) not null default '1', "card_number" varchar, "insurance_number" varchar, foreign key("manager_id") references employees("id") on delete set null on update no action, foreign key("job_position_id") references job_positions("id") on delete set null on update no action, foreign key("department_id") references departments("id") on delete set null on update no action, foreign key("user_id") references users("id") on delete set null on update no action, foreign key("sales_territory_id") references "sales_territories"("id") on delete set null);

CREATE TABLE "failed_jobs" ("id" integer primary key autoincrement not null, "uuid" varchar not null, "connection" text not null, "queue" text not null, "payload" text not null, "exception" text not null, "failed_at" datetime not null default CURRENT_TIMESTAMP);

CREATE TABLE "governorates" ("id" integer primary key autoincrement not null, "name" varchar not null, "code" varchar, "is_active" tinyint(1) not null default '1', "created_at" datetime, "updated_at" datetime, "deleted_at" datetime);

CREATE TABLE "inventory_movements" ("id" integer primary key autoincrement not null, "product_id" integer not null, "warehouse_id" integer not null, "movement_type" varchar not null, "reference_type" varchar, "reference_id" integer, "quantity" numeric not null, "unit_cost" numeric not null default '0', "movement_date" date not null, "created_by" integer, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, foreign key("product_id") references "products"("id") on delete cascade, foreign key("warehouse_id") references "warehouses"("id") on delete cascade, foreign key("created_by") references "users"("id") on delete set null);

CREATE TABLE "invoice_items" ("id" integer primary key autoincrement not null, "invoice_id" integer not null, "product_id" integer not null, "quantity" numeric not null, "price" numeric not null, "discount" numeric not null default '0', "total" numeric not null, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, foreign key("invoice_id") references "invoices"("id") on delete cascade, foreign key("product_id") references "products"("id") on delete cascade);

CREATE TABLE "invoices" ("id" integer primary key autoincrement not null, "invoice_no" varchar not null, "customer_id" integer not null, "representative_id" integer, "invoice_date" date not null, "subtotal" numeric not null default '0', "discount" numeric not null default '0', "tax" numeric not null default '0', "total" numeric not null default '0', "paid_amount" numeric not null default '0', "remaining_amount" numeric not null default '0', "status" varchar check ("status" in ('draft', 'paid', 'partial', 'unpaid', 'cancelled')) not null default 'draft', "notes" text, "created_by" integer, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, foreign key("customer_id") references "customers"("id") on delete cascade, foreign key("representative_id") references "representatives"("id") on delete set null, foreign key("created_by") references "users"("id") on delete set null);

CREATE TABLE "job_batches" ("id" varchar not null, "name" varchar not null, "total_jobs" integer not null, "pending_jobs" integer not null, "failed_jobs" integer not null, "failed_job_ids" text not null, "options" text, "cancelled_at" integer, "created_at" integer not null, "finished_at" integer, primary key ("id"));

CREATE TABLE "job_positions" ("id" integer primary key autoincrement not null, "code" varchar not null, "name" varchar not null, "description" text, "is_active" tinyint(1) not null default ('1'), "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, "department_id" integer, "parent_id" integer, "sort_order" integer not null default ('0'), "position_level_id" integer, foreign key("parent_id") references job_positions("id") on delete set null on update no action, foreign key("department_id") references departments("id") on delete set null on update no action, foreign key("position_level_id") references "position_levels"("id") on delete set null);

CREATE TABLE "jobs" ("id" integer primary key autoincrement not null, "queue" varchar not null, "payload" text not null, "attempts" integer not null, "reserved_at" integer, "available_at" integer not null, "created_at" integer not null);

CREATE TABLE "leave_requests" ("id" integer primary key autoincrement not null, "employee_id" integer not null, "leave_type_id" integer not null, "start_date" date not null, "end_date" date not null, "days_count" numeric not null, "reason" text, "status" varchar not null default 'pending', "approved_by" integer, "approved_at" datetime, "rejection_reason" text, "notes" text, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, foreign key("employee_id") references "employees"("id") on delete cascade, foreign key("leave_type_id") references "leave_types"("id") on delete restrict, foreign key("approved_by") references "users"("id") on delete set null);

CREATE TABLE "leave_types" ("id" integer primary key autoincrement not null, "code" varchar not null, "name" varchar not null, "description" text, "max_days_per_year" integer, "is_paid" tinyint(1) not null default '1', "requires_approval" tinyint(1) not null default '1', "is_active" tinyint(1) not null default '1', "created_at" datetime, "updated_at" datetime, "deleted_at" datetime);

CREATE TABLE "migrations" ("id" integer primary key autoincrement not null, "migration" varchar not null, "batch" integer not null);

CREATE TABLE "notifications" ("id" integer primary key autoincrement not null, "user_id" integer not null, "title" varchar not null, "message" text not null, "is_read" tinyint(1) not null default '0', "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, foreign key("user_id") references "users"("id") on delete cascade);

CREATE TABLE "password_reset_tokens" ("email" varchar not null, "token" varchar not null, "created_at" datetime, primary key ("email"));

CREATE TABLE "payroll_items" ("id" integer primary key autoincrement not null, "payroll_run_id" integer not null, "employee_id" integer not null, "basic_salary" numeric not null default '0', "total_allowances" numeric not null default '0', "total_deductions" numeric not null default '0', "bonus_amount" numeric not null default '0', "advance_deduction" numeric not null default '0', "net_salary" numeric not null default '0', "working_days" integer not null default '0', "present_days" integer not null default '0', "absent_days" integer not null default '0', "leave_days" numeric not null default '0', "late_days" integer not null default '0', "notes" text, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, "commission_amount" numeric not null default '0', "target_amount" numeric not null default '0', "achievement_percentage" numeric not null default '0', foreign key("payroll_run_id") references "payroll_runs"("id") on delete cascade, foreign key("employee_id") references "employees"("id") on delete cascade);

CREATE TABLE "payroll_runs" ("id" integer primary key autoincrement not null, "period_year" integer not null, "period_month" integer not null, "title" varchar not null, "status" varchar not null default 'draft', "working_days" integer not null default '30', "processed_at" datetime, "processed_by" integer, "approved_at" datetime, "approved_by" integer, "notes" text, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, foreign key("processed_by") references "users"("id") on delete set null, foreign key("approved_by") references "users"("id") on delete set null);

CREATE TABLE "personal_access_tokens" ("id" integer primary key autoincrement not null, "tokenable_type" varchar not null, "tokenable_id" integer not null, "name" text not null, "token" varchar not null, "abilities" text, "last_used_at" datetime, "expires_at" datetime, "created_at" datetime, "updated_at" datetime);

CREATE TABLE "position_levels" ("id" integer primary key autoincrement not null, "code" varchar not null, "name" varchar not null, "description" text, "sort_order" integer not null default '0', "is_active" tinyint(1) not null default '1', "created_at" datetime, "updated_at" datetime, "deleted_at" datetime);

CREATE TABLE "price_list_items" ("id" integer primary key autoincrement not null, "price_list_id" integer not null, "product_id" integer not null, "unit_id" integer, "price" numeric not null default ('0'), "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, foreign key("unit_id") references units("id") on delete set null on update no action, foreign key("product_id") references products("id") on delete cascade on update no action, foreign key("price_list_id") references price_lists("id") on delete cascade on update no action);

CREATE TABLE "price_list_product_price" ("id" integer primary key autoincrement not null, "price_list_id" integer not null, "product_price_id" integer not null, "created_at" datetime, "updated_at" datetime, foreign key("price_list_id") references "price_lists"("id") on delete cascade, foreign key("product_price_id") references "product_prices"("id") on delete cascade);

CREATE TABLE "price_lists" ("id" integer primary key autoincrement not null, "name" varchar not null, "description" text, "is_default" tinyint(1) not null default '1', "created_at" datetime, "updated_at" datetime, "deleted_at" datetime);

CREATE TABLE "product_prices" ("id" integer primary key autoincrement not null, "product_id" integer not null, "purchase_price" numeric not null default ('0'), "sale_price" numeric not null default ('0'), "effective_from" date, "notes" text, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, "sub_category_id" integer, "unit_id" integer, "quantity_per_unit" numeric not null default ('1'), "level_no" integer not null default ('1'), "is_primary_unit" tinyint(1) not null default ('0'), foreign key("unit_id") references units("id") on delete set null on update no action, foreign key("product_id") references products("id") on delete cascade on update no action, foreign key("sub_category_id") references sub_categories("id") on delete set null on update no action);

CREATE TABLE "product_stocks" ("id" integer primary key autoincrement not null, "warehouse_id" integer not null, "product_id" integer not null, "quantity" numeric not null default '0', "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, foreign key("warehouse_id") references "warehouses"("id") on delete cascade, foreign key("product_id") references "products"("id") on delete cascade);

CREATE TABLE "products" ("id" integer primary key autoincrement not null, "code" varchar not null, "barcode" varchar, "name" varchar not null, "category_id" integer, "unit_id" integer, "purchase_price" numeric not null default ('0'), "sale_price" numeric not null default ('0'), "min_stock" integer not null default ('0'), "tax_rate" numeric not null default ('0'), "description" text, "is_active" tinyint(1) not null default ('1'), "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, "sub_category_id" integer, foreign key("unit_id") references units("id") on delete set null on update no action, foreign key("category_id") references categories("id") on delete set null on update no action, foreign key("sub_category_id") references "sub_categories"("id") on delete set null);

CREATE TABLE "public_holidays" ("id" integer primary key autoincrement not null, "name" varchar not null, "holiday_date" date not null, "is_recurring" tinyint(1) not null default '0', "notes" text, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime);

CREATE TABLE "purchase_items" ("id" integer primary key autoincrement not null, "purchase_id" integer not null, "product_id" integer not null, "quantity" numeric not null, "price" numeric not null, "discount" numeric not null default '0', "total" numeric not null, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, foreign key("purchase_id") references "purchases"("id") on delete cascade, foreign key("product_id") references "products"("id") on delete cascade);

CREATE TABLE "purchases" ("id" integer primary key autoincrement not null, "invoice_no" varchar not null, "supplier_id" integer not null, "purchase_date" date not null, "subtotal" numeric not null default '0', "discount" numeric not null default '0', "tax" numeric not null default '0', "total" numeric not null default '0', "status" varchar not null default 'draft', "notes" text, "created_by" integer, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, foreign key("supplier_id") references "suppliers"("id") on delete cascade, foreign key("created_by") references "users"("id") on delete set null);

CREATE TABLE "rep_return_order_items" ("id" integer primary key autoincrement not null, "rep_return_order_id" integer not null, "product_id" integer not null, "quantity" numeric not null, "unit_cost" numeric not null default '0', "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, foreign key("rep_return_order_id") references "rep_return_orders"("id") on delete cascade, foreign key("product_id") references "products"("id") on delete cascade);

CREATE TABLE "rep_return_orders" ("id" integer primary key autoincrement not null, "order_no" varchar not null, "warehouse_id" integer not null, "representative_id" integer not null, "return_date" date not null, "status" varchar check ("status" in ('draft', 'pending', 'approved', 'cancelled')) not null default 'draft', "notes" text, "created_by" integer, "approved_by" integer, "approved_at" datetime, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, foreign key("warehouse_id") references "warehouses"("id") on delete cascade, foreign key("representative_id") references "representatives"("id") on delete cascade, foreign key("created_by") references "users"("id") on delete set null, foreign key("approved_by") references "users"("id") on delete set null);

CREATE TABLE "representative_stock_movements" ("id" integer primary key autoincrement not null, "representative_id" integer not null, "product_id" integer not null, "movement_type" varchar not null, "reference_type" varchar, "reference_id" integer, "quantity" numeric not null, "movement_date" date not null, "created_by" integer, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, foreign key("representative_id") references "representatives"("id") on delete cascade, foreign key("product_id") references "products"("id") on delete cascade, foreign key("created_by") references "users"("id") on delete set null);

CREATE TABLE "representative_stocks" ("id" integer primary key autoincrement not null, "representative_id" integer not null, "product_id" integer not null, "quantity" numeric not null default '0', "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, foreign key("representative_id") references "representatives"("id") on delete cascade, foreign key("product_id") references "products"("id") on delete cascade);

CREATE TABLE "representatives" ("id" integer primary key autoincrement not null, "user_id" integer not null, "target_amount" numeric not null default ('0'), "commission_rate" numeric not null default ('0'), "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, "sales_territory_id" integer, foreign key("user_id") references users("id") on delete cascade on update no action, foreign key("sales_territory_id") references "sales_territories"("id") on delete set null);

CREATE TABLE "role_admin_screen" ("id" integer primary key autoincrement not null, "role_id" integer not null, "admin_screen_id" integer not null, "created_at" datetime, "updated_at" datetime, foreign key("role_id") references "roles"("id") on delete cascade, foreign key("admin_screen_id") references "admin_screens"("id") on delete cascade);

CREATE TABLE "roles" ("id" integer primary key autoincrement not null, "name" varchar not null, "description" varchar, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime);

CREATE TABLE "salary_components" ("id" integer primary key autoincrement not null, "code" varchar not null, "name" varchar not null, "component_type" varchar not null, "is_taxable" tinyint(1) not null default '0', "is_fixed" tinyint(1) not null default '1', "description" text, "is_active" tinyint(1) not null default '1', "created_at" datetime, "updated_at" datetime, "deleted_at" datetime);

CREATE TABLE "sales_return_items" ("id" integer primary key autoincrement not null, "sales_return_id" integer not null, "product_id" integer not null, "quantity" numeric not null, "price" numeric not null, "total" numeric not null, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, foreign key("sales_return_id") references "sales_returns"("id") on delete cascade, foreign key("product_id") references "products"("id") on delete cascade);

CREATE TABLE "sales_returns" ("id" integer primary key autoincrement not null, "invoice_id" integer not null, "customer_id" integer not null, "return_date" date not null, "total_amount" numeric not null default '0', "notes" text, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, foreign key("invoice_id") references "invoices"("id") on delete cascade, foreign key("customer_id") references "customers"("id") on delete cascade);

CREATE TABLE "sales_territories" ("id" integer primary key autoincrement not null, "governorate_id" integer not null, "name" varchar not null, "code" varchar, "description" text, "is_active" tinyint(1) not null default '1', "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, foreign key("governorate_id") references "governorates"("id") on delete cascade);

CREATE TABLE "sessions" ("id" varchar not null, "user_id" integer, "ip_address" varchar, "user_agent" text, "payload" text not null, "last_activity" integer not null, primary key ("id"));

CREATE TABLE "streets" ("id" integer primary key autoincrement not null, "area_id" integer not null, "name" varchar not null, "is_active" tinyint(1) not null default '1', "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, foreign key("area_id") references "areas"("id") on delete cascade);

CREATE TABLE "sub_categories" ("id" integer primary key autoincrement not null, "category_id" integer not null, "name" varchar not null, "description" text, "is_active" tinyint(1) not null default '1', "sort_order" integer not null default '0', "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, foreign key("category_id") references "categories"("id") on delete cascade);

CREATE TABLE "supplier_payments" ("id" integer primary key autoincrement not null, "supplier_id" integer not null, "purchase_id" integer, "payment_date" date not null, "amount" numeric not null, "payment_method" varchar not null, "notes" text, "created_by" integer, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, foreign key("supplier_id") references "suppliers"("id") on delete cascade, foreign key("purchase_id") references "purchases"("id") on delete set null, foreign key("created_by") references "users"("id") on delete set null);

CREATE TABLE "suppliers" ("id" integer primary key autoincrement not null, "code" varchar not null, "name" varchar not null, "phone" varchar, "mobile" varchar, "email" varchar, "address" text, "notes" text, "current_balance" numeric not null default '0', "created_at" datetime, "updated_at" datetime, "deleted_at" datetime);

CREATE TABLE "units" ("id" integer primary key autoincrement not null, "name" varchar not null, "short_name" varchar, "description" text, "is_active" tinyint(1) not null default ('1'), "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, "sub_category_id" integer, foreign key("sub_category_id") references "sub_categories"("id") on delete set null);

CREATE TABLE "user_roles" ("id" integer primary key autoincrement not null, "user_id" integer not null, "role_id" integer not null, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, foreign key("user_id") references "users"("id") on delete cascade, foreign key("role_id") references "roles"("id") on delete cascade);

CREATE TABLE "users" ("id" integer primary key autoincrement not null, "usercode" integer not null, "name" varchar not null, "email" varchar, "password" varchar not null, "phone" varchar, "is_active" tinyint(1) not null default '1', "created_at" datetime, "updated_at" datetime, "deleted_at" datetime);

CREATE TABLE "visits" ("id" integer primary key autoincrement not null, "representative_id" integer not null, "customer_id" integer not null, "visit_date" date not null, "check_in" time, "check_out" time, "latitude" numeric, "longitude" numeric, "notes" text, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, foreign key("representative_id") references "representatives"("id") on delete cascade, foreign key("customer_id") references "customers"("id") on delete cascade);

CREATE TABLE "warehouses" ("id" integer primary key autoincrement not null, "name" varchar not null, "address" text, "manager_id" integer, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, foreign key("manager_id") references "users"("id") on delete set null);

CREATE TABLE "work_shifts" ("id" integer primary key autoincrement not null, "code" varchar not null, "name" varchar not null, "start_time" time not null, "end_time" time not null, "break_minutes" integer not null default '0', "late_grace_minutes" integer not null default '15', "is_active" tinyint(1) not null default '1', "created_at" datetime, "updated_at" datetime, "deleted_at" datetime);
